package org.ehais.weixin.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.ehais.weixin.model.HaiArticle;
import org.ehais.weixin.model.HaiArticleExample;

public interface HaiArticleMapper {
	//tyler
	@ResultMap(value = "BaseResultMap")
	public List<HaiArticle> article_list(
			@Param("store_id") Integer store_id,
			@Param("cat_id") Integer cat_id,
			@Param("start") Integer start,
			@Param("len") Integer len
			);
	
	@ResultMap(value = "BaseResultMap")
	public List<HaiArticle> article_list_v2(
			@Param("store_id") Integer store_id,
			@Param("cat_id") Integer cat_id,
			@Param("start") Integer start,
			@Param("len") Integer len
			);
	
	@ResultMap(value = "BaseResultMap")
	public List<HaiArticle> article_list_by_catcode(
			@Param("store_id") Integer store_id,
			@Param("code") String code,
			@Param("start") Integer start,
			@Param("len") Integer len
			);
	
	
	@Select("select * from hai_article where store_id = #{store_id} and ifnull(code,'') != '' order by article_id desc limit #{start},#{len}")
	@ResultMap(value = "BaseResultMap")
	public List<HaiArticle> article_code_list(
			@Param("store_id") Integer store_id,
			@Param("start") Integer start,
			@Param("len") Integer len
			);
	
	@Select("select * from hai_article where store_id = #{store_id} and code = #{code} order by article_id desc limit 0,1")
	@ResultMap(value = "BaseResultMap")
	public HaiArticle article_code(
			@Param("store_id") Integer store_id,
			@Param("code") String code
			);
	
	@Select("select * from hai_article where store_id = #{store_id} and article_id in (${article_ids}) order by article_id desc limit #{start},#{len}")
	@ResultMap(value = "BaseResultMap")
	public List<HaiArticle> article_mult_list(
			@Param("store_id") Integer store_id,
			@Param("article_ids") String article_ids,
			@Param("start") Integer start,
			@Param("len") Integer len
			);
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_article
     *
     * @mbggenerated Tue Mar 01 11:26:51 CST 2016
     */
    int countByExample(HaiArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_article
     *
     * @mbggenerated Tue Mar 01 11:26:51 CST 2016
     */
    int deleteByExample(HaiArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_article
     *
     * @mbggenerated Tue Mar 01 11:26:51 CST 2016
     */
    int deleteByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_article
     *
     * @mbggenerated Tue Mar 01 11:26:51 CST 2016
     */
    int insert(HaiArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_article
     *
     * @mbggenerated Tue Mar 01 11:26:51 CST 2016
     */
    int insertSelective(HaiArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_article
     *
     * @mbggenerated Tue Mar 01 11:26:51 CST 2016
     */
    List<HaiArticle> selectByExampleWithBLOBs(HaiArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_article
     *
     * @mbggenerated Tue Mar 01 11:26:51 CST 2016
     */
    List<HaiArticle> selectByExample(HaiArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_article
     *
     * @mbggenerated Tue Mar 01 11:26:51 CST 2016
     */
    HaiArticle selectByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_article
     *
     * @mbggenerated Tue Mar 01 11:26:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") HaiArticle record, @Param("example") HaiArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_article
     *
     * @mbggenerated Tue Mar 01 11:26:51 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") HaiArticle record, @Param("example") HaiArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_article
     *
     * @mbggenerated Tue Mar 01 11:26:51 CST 2016
     */
    int updateByExample(@Param("record") HaiArticle record, @Param("example") HaiArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_article
     *
     * @mbggenerated Tue Mar 01 11:26:51 CST 2016
     */
    int updateByPrimaryKeySelective(HaiArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_article
     *
     * @mbggenerated Tue Mar 01 11:26:51 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(HaiArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_article
     *
     * @mbggenerated Tue Mar 01 11:26:51 CST 2016
     */
    int updateByPrimaryKey(HaiArticle record);
}