package org.ehais.weixin.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.ehais.weixin.model.HaiDonation;
import org.ehais.weixin.model.HaiDonationExample;

public interface HaiDonationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_donation
     *
     * @mbggenerated Wed Oct 26 21:31:28 CST 2016
     */
    @ResultMap(value = "BaseResultMap")
    List<HaiDonation> hai_donation_list(@Param("store_id") Integer store_id, @Param("start") Integer start, @Param("len") Integer len);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_donation
     *
     * @mbggenerated Wed Oct 26 21:31:28 CST 2016
     */
    @ResultMap(value = "BaseResultMap")
    List<HaiDonation> hai_donation_list_by_example(HaiDonationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_donation
     *
     * @mbggenerated Wed Oct 26 21:31:28 CST 2016
     */
    @ResultMap(value = "ResultMapWithBLOBs")
    HaiDonation get_hai_donation_info(@Param("store_id") Integer store_id, @Param("donation_id") Integer donation_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_donation
     *
     * @mbggenerated Wed Oct 26 21:31:28 CST 2016
     */
    int countByExample(HaiDonationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_donation
     *
     * @mbggenerated Wed Oct 26 21:31:28 CST 2016
     */
    int deleteByExample(HaiDonationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_donation
     *
     * @mbggenerated Wed Oct 26 21:31:28 CST 2016
     */
    int deleteByPrimaryKey(Integer donationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_donation
     *
     * @mbggenerated Wed Oct 26 21:31:28 CST 2016
     */
    int insert(HaiDonation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_donation
     *
     * @mbggenerated Wed Oct 26 21:31:28 CST 2016
     */
    int insertSelective(HaiDonation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_donation
     *
     * @mbggenerated Wed Oct 26 21:31:28 CST 2016
     */
    List<HaiDonation> selectByExampleWithBLOBs(HaiDonationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_donation
     *
     * @mbggenerated Wed Oct 26 21:31:28 CST 2016
     */
    List<HaiDonation> selectByExample(HaiDonationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_donation
     *
     * @mbggenerated Wed Oct 26 21:31:28 CST 2016
     */
    HaiDonation selectByPrimaryKey(Integer donationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_donation
     *
     * @mbggenerated Wed Oct 26 21:31:28 CST 2016
     */
    int updateByExampleSelective(@Param("record") HaiDonation record, @Param("example") HaiDonationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_donation
     *
     * @mbggenerated Wed Oct 26 21:31:28 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") HaiDonation record, @Param("example") HaiDonationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_donation
     *
     * @mbggenerated Wed Oct 26 21:31:28 CST 2016
     */
    int updateByExample(@Param("record") HaiDonation record, @Param("example") HaiDonationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_donation
     *
     * @mbggenerated Wed Oct 26 21:31:28 CST 2016
     */
    int updateByPrimaryKeySelective(HaiDonation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_donation
     *
     * @mbggenerated Wed Oct 26 21:31:28 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(HaiDonation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_donation
     *
     * @mbggenerated Wed Oct 26 21:31:28 CST 2016
     */
    int updateByPrimaryKey(HaiDonation record);
}