package com.ehais.tracking.entity;
// default package
// Generated 2016-3-22 19:54:34 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HaiAdminUser generated by hbm2java
 */
@Entity
@Table(name = "hai_admin_user", catalog = "tracking")
public class HaiAdminUser implements java.io.Serializable {

	private Short adminId;
	private String userName;
	private String email;
	private String password;
	private String ecSalt;
	private Integer addTime;
	private Integer lastLogin;
	private String lastIp;
	private String actionList;
	private String navList;
	private String langType;
	private Short agencyId;
	private Short businessId;
	private String todolist;
	private Integer storeId;
	private String projectFolder;

	public HaiAdminUser() {
	}

	public HaiAdminUser(String userName, String email, String password) {
		this.userName = userName;
		this.email = email;
		this.password = password;
	}

	public HaiAdminUser(String userName, String email, String password,
			String ecSalt, Integer addTime, Integer lastLogin, String lastIp,
			String actionList, String navList, String langType, Short agencyId,
			Short businessId, String todolist, Integer storeId,
			String projectFolder) {
		this.userName = userName;
		this.email = email;
		this.password = password;
		this.ecSalt = ecSalt;
		this.addTime = addTime;
		this.lastLogin = lastLogin;
		this.lastIp = lastIp;
		this.actionList = actionList;
		this.navList = navList;
		this.langType = langType;
		this.agencyId = agencyId;
		this.businessId = businessId;
		this.todolist = todolist;
		this.storeId = storeId;
		this.projectFolder = projectFolder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "admin_id", unique = true, nullable = false)
	public Short getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Short adminId) {
		this.adminId = adminId;
	}

	@Column(name = "user_name", nullable = false, length = 60)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "email", nullable = false, length = 60)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ec_salt", length = 10)
	public String getEcSalt() {
		return this.ecSalt;
	}

	public void setEcSalt(String ecSalt) {
		this.ecSalt = ecSalt;
	}

	@Column(name = "add_time")
	public Integer getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Integer addTime) {
		this.addTime = addTime;
	}

	@Column(name = "last_login")
	public Integer getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Integer lastLogin) {
		this.lastLogin = lastLogin;
	}

	@Column(name = "last_ip", length = 15)
	public String getLastIp() {
		return this.lastIp;
	}

	public void setLastIp(String lastIp) {
		this.lastIp = lastIp;
	}

	@Column(name = "action_list", length = 65535)
	public String getActionList() {
		return this.actionList;
	}

	public void setActionList(String actionList) {
		this.actionList = actionList;
	}

	@Column(name = "nav_list", length = 65535)
	public String getNavList() {
		return this.navList;
	}

	public void setNavList(String navList) {
		this.navList = navList;
	}

	@Column(name = "lang_type", length = 50)
	public String getLangType() {
		return this.langType;
	}

	public void setLangType(String langType) {
		this.langType = langType;
	}

	@Column(name = "agency_id")
	public Short getAgencyId() {
		return this.agencyId;
	}

	public void setAgencyId(Short agencyId) {
		this.agencyId = agencyId;
	}

	@Column(name = "business_id")
	public Short getBusinessId() {
		return this.businessId;
	}

	public void setBusinessId(Short businessId) {
		this.businessId = businessId;
	}

	@Column(name = "todolist")
	public String getTodolist() {
		return this.todolist;
	}

	public void setTodolist(String todolist) {
		this.todolist = todolist;
	}

	@Column(name = "store_id")
	public Integer getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}

	@Column(name = "project_folder", length = 20)
	public String getProjectFolder() {
		return this.projectFolder;
	}

	public void setProjectFolder(String projectFolder) {
		this.projectFolder = projectFolder;
	}

}
