package com.ehais.tracking.entity;
// default package
// Generated 2016-3-22 19:54:34 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ThinkAccessId generated by hbm2java
 */
@Embeddable
public class ThinkAccessId implements java.io.Serializable {

	private short roleId;
	private short nodeId;

	public ThinkAccessId() {
	}

	public ThinkAccessId(short roleId, short nodeId) {
		this.roleId = roleId;
		this.nodeId = nodeId;
	}

	@Column(name = "role_id", nullable = false)
	public short getRoleId() {
		return this.roleId;
	}

	public void setRoleId(short roleId) {
		this.roleId = roleId;
	}

	@Column(name = "node_id", nullable = false)
	public short getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(short nodeId) {
		this.nodeId = nodeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ThinkAccessId))
			return false;
		ThinkAccessId castOther = (ThinkAccessId) other;

		return (this.getRoleId() == castOther.getRoleId())
				&& (this.getNodeId() == castOther.getNodeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoleId();
		result = 37 * result + this.getNodeId();
		return result;
	}

}
