package org.ehais.shop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.ehais.shop.model.HaiActivityParticipation;
import org.ehais.shop.model.HaiActivityParticipationExample;

public interface HaiActivityParticipationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_activity_participation
     *
     * @mbg.generated Sun Oct 15 20:54:28 CST 2017
     */
    @Select("select count(*) from hai_activity_participation where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_activity_participation
     *
     * @mbg.generated Sun Oct 15 20:54:28 CST 2017
     */
    @Select("select count(*) from hai_activity_participation where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_activity_participation
     *
     * @mbg.generated Sun Oct 15 20:54:28 CST 2017
     */
    long countByExample(HaiActivityParticipationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_activity_participation
     *
     * @mbg.generated Sun Oct 15 20:54:28 CST 2017
     */
    int deleteByExample(HaiActivityParticipationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_activity_participation
     *
     * @mbg.generated Sun Oct 15 20:54:28 CST 2017
     */
    int deleteByPrimaryKey(Long participationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_activity_participation
     *
     * @mbg.generated Sun Oct 15 20:54:28 CST 2017
     */
    int insert(HaiActivityParticipation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_activity_participation
     *
     * @mbg.generated Sun Oct 15 20:54:28 CST 2017
     */
    int insertSelective(HaiActivityParticipation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_activity_participation
     *
     * @mbg.generated Sun Oct 15 20:54:28 CST 2017
     */
    List<HaiActivityParticipation> selectByExample(HaiActivityParticipationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_activity_participation
     *
     * @mbg.generated Sun Oct 15 20:54:28 CST 2017
     */
    HaiActivityParticipation selectByPrimaryKey(Long participationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_activity_participation
     *
     * @mbg.generated Sun Oct 15 20:54:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") HaiActivityParticipation record, @Param("example") HaiActivityParticipationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_activity_participation
     *
     * @mbg.generated Sun Oct 15 20:54:28 CST 2017
     */
    int updateByExample(@Param("record") HaiActivityParticipation record, @Param("example") HaiActivityParticipationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_activity_participation
     *
     * @mbg.generated Sun Oct 15 20:54:28 CST 2017
     */
    int updateByPrimaryKeySelective(HaiActivityParticipation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_activity_participation
     *
     * @mbg.generated Sun Oct 15 20:54:28 CST 2017
     */
    int updateByPrimaryKey(HaiActivityParticipation record);
}