package org.ehais.shop.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.ehais.epublic.model.EHaiAdPosition;
import org.ehais.epublic.model.EHaiAdPositionExample;

public interface HaiAdPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_ad_position
     *
     * @mbggenerated Thu Apr 14 23:08:24 CST 2016
     */
    @ResultMap(value = "BaseResultMap")
    List<EHaiAdPosition> hai_ad_position_list(@Param("store_id") Integer store_id, @Param("start") Integer start, @Param("len") Integer len);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_ad_position
     *
     * @mbggenerated Thu Apr 14 23:08:24 CST 2016
     */
    @ResultMap(value = "BaseResultMap")
    List<EHaiAdPosition> hai_ad_position_list_by_example(EHaiAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_ad_position
     *
     * @mbggenerated Thu Apr 14 23:08:24 CST 2016
     */
    int countByExample(EHaiAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_ad_position
     *
     * @mbggenerated Thu Apr 14 23:08:24 CST 2016
     */
    int deleteByExample(EHaiAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_ad_position
     *
     * @mbggenerated Thu Apr 14 23:08:24 CST 2016
     */
    int deleteByPrimaryKey(Short positionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_ad_position
     *
     * @mbggenerated Thu Apr 14 23:08:24 CST 2016
     */
    int insert(EHaiAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_ad_position
     *
     * @mbggenerated Thu Apr 14 23:08:24 CST 2016
     */
    int insertSelective(EHaiAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_ad_position
     *
     * @mbggenerated Thu Apr 14 23:08:24 CST 2016
     */
    List<EHaiAdPosition> selectByExampleWithBLOBs(EHaiAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_ad_position
     *
     * @mbggenerated Thu Apr 14 23:08:24 CST 2016
     */
    List<EHaiAdPosition> selectByExample(EHaiAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_ad_position
     *
     * @mbggenerated Thu Apr 14 23:08:24 CST 2016
     */
    EHaiAdPosition selectByPrimaryKey(Short positionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_ad_position
     *
     * @mbggenerated Thu Apr 14 23:08:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") EHaiAdPosition record, @Param("example") EHaiAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_ad_position
     *
     * @mbggenerated Thu Apr 14 23:08:24 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") EHaiAdPosition record, @Param("example") EHaiAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_ad_position
     *
     * @mbggenerated Thu Apr 14 23:08:24 CST 2016
     */
    int updateByExample(@Param("record") EHaiAdPosition record, @Param("example") EHaiAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_ad_position
     *
     * @mbggenerated Thu Apr 14 23:08:24 CST 2016
     */
    int updateByPrimaryKeySelective(EHaiAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_ad_position
     *
     * @mbggenerated Thu Apr 14 23:08:24 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(EHaiAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_ad_position
     *
     * @mbggenerated Thu Apr 14 23:08:24 CST 2016
     */
    int updateByPrimaryKey(EHaiAdPosition record);
}