package org.ehais.shop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.ehais.shop.model.HaiCoupons;
import org.ehais.shop.model.HaiCouponsExample;

public interface HaiCouponsMapper {
	
	
	@ResultMap(value = "BaseResultMap")
	List<HaiCoupons> selectStoreCoupons(@Param("store_id") Integer store_id);

	
    long countStoreCoupons(@Param("store_id") Integer store_id);

	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_coupons
     *
     * @mbg.generated Tue Nov 14 20:05:47 CST 2017
     */
    @Select("select count(*) from hai_coupons where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_coupons
     *
     * @mbg.generated Tue Nov 14 20:05:47 CST 2017
     */
    @Select("select count(*) from hai_coupons where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_coupons
     *
     * @mbg.generated Tue Nov 14 20:05:47 CST 2017
     */
    long countByExample(HaiCouponsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_coupons
     *
     * @mbg.generated Tue Nov 14 20:05:47 CST 2017
     */
    int deleteByExample(HaiCouponsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_coupons
     *
     * @mbg.generated Tue Nov 14 20:05:47 CST 2017
     */
    int deleteByPrimaryKey(Integer couponsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_coupons
     *
     * @mbg.generated Tue Nov 14 20:05:47 CST 2017
     */
    int insert(HaiCoupons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_coupons
     *
     * @mbg.generated Tue Nov 14 20:05:47 CST 2017
     */
    int insertSelective(HaiCoupons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_coupons
     *
     * @mbg.generated Tue Nov 14 20:05:47 CST 2017
     */
    List<HaiCoupons> selectByExample(HaiCouponsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_coupons
     *
     * @mbg.generated Tue Nov 14 20:05:47 CST 2017
     */
    HaiCoupons selectByPrimaryKey(Integer couponsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_coupons
     *
     * @mbg.generated Tue Nov 14 20:05:47 CST 2017
     */
    int updateByExampleSelective(@Param("record") HaiCoupons record, @Param("example") HaiCouponsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_coupons
     *
     * @mbg.generated Tue Nov 14 20:05:47 CST 2017
     */
    int updateByExample(@Param("record") HaiCoupons record, @Param("example") HaiCouponsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_coupons
     *
     * @mbg.generated Tue Nov 14 20:05:47 CST 2017
     */
    int updateByPrimaryKeySelective(HaiCoupons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_coupons
     *
     * @mbg.generated Tue Nov 14 20:05:47 CST 2017
     */
    int updateByPrimaryKey(HaiCoupons record);
}