package org.ehais.shop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.ehais.shop.model.HaiGuestbook;
import org.ehais.shop.model.HaiGuestbookExample;
import org.ehais.shop.model.HaiGuestbookWithBLOBs;

public interface HaiGuestbookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_guestbook
     *
     * @mbg.generated Thu Jan 04 20:12:41 CST 2018
     */
    @Select("select count(*) from hai_guestbook where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_guestbook
     *
     * @mbg.generated Thu Jan 04 20:12:41 CST 2018
     */
    @Select("select count(*) from hai_guestbook where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_guestbook
     *
     * @mbg.generated Thu Jan 04 20:12:41 CST 2018
     */
    long countByExample(HaiGuestbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_guestbook
     *
     * @mbg.generated Thu Jan 04 20:12:41 CST 2018
     */
    int deleteByExample(HaiGuestbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_guestbook
     *
     * @mbg.generated Thu Jan 04 20:12:41 CST 2018
     */
    int deleteByPrimaryKey(Integer guestbookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_guestbook
     *
     * @mbg.generated Thu Jan 04 20:12:41 CST 2018
     */
    int insert(HaiGuestbookWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_guestbook
     *
     * @mbg.generated Thu Jan 04 20:12:41 CST 2018
     */
    int insertSelective(HaiGuestbookWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_guestbook
     *
     * @mbg.generated Thu Jan 04 20:12:41 CST 2018
     */
    List<HaiGuestbookWithBLOBs> selectByExampleWithBLOBs(HaiGuestbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_guestbook
     *
     * @mbg.generated Thu Jan 04 20:12:41 CST 2018
     */
    List<HaiGuestbook> selectByExample(HaiGuestbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_guestbook
     *
     * @mbg.generated Thu Jan 04 20:12:41 CST 2018
     */
    HaiGuestbookWithBLOBs selectByPrimaryKey(Integer guestbookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_guestbook
     *
     * @mbg.generated Thu Jan 04 20:12:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") HaiGuestbookWithBLOBs record, @Param("example") HaiGuestbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_guestbook
     *
     * @mbg.generated Thu Jan 04 20:12:41 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") HaiGuestbookWithBLOBs record, @Param("example") HaiGuestbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_guestbook
     *
     * @mbg.generated Thu Jan 04 20:12:41 CST 2018
     */
    int updateByExample(@Param("record") HaiGuestbook record, @Param("example") HaiGuestbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_guestbook
     *
     * @mbg.generated Thu Jan 04 20:12:41 CST 2018
     */
    int updateByPrimaryKeySelective(HaiGuestbookWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_guestbook
     *
     * @mbg.generated Thu Jan 04 20:12:41 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(HaiGuestbookWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_guestbook
     *
     * @mbg.generated Thu Jan 04 20:12:41 CST 2018
     */
    int updateByPrimaryKey(HaiGuestbook record);
}