package org.ehais.shop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.ehais.shop.model.HaiGoodsAttr;
import org.ehais.shop.model.HaiGoodsAttrExample;

public interface HaiGoodsAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_attr
     *
     * @mbg.generated Tue Oct 10 18:36:52 CST 2017
     */
    @Select("select count(*) from hai_goods_attr where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_attr
     *
     * @mbg.generated Tue Oct 10 18:36:52 CST 2017
     */
    @Select("select count(*) from hai_goods_attr where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_attr
     *
     * @mbg.generated Tue Oct 10 18:36:52 CST 2017
     */
    long countByExample(HaiGoodsAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_attr
     *
     * @mbg.generated Tue Oct 10 18:36:52 CST 2017
     */
    int deleteByExample(HaiGoodsAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_attr
     *
     * @mbg.generated Tue Oct 10 18:36:52 CST 2017
     */
    int deleteByPrimaryKey(Long goodsAttrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_attr
     *
     * @mbg.generated Tue Oct 10 18:36:52 CST 2017
     */
    int insert(HaiGoodsAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_attr
     *
     * @mbg.generated Tue Oct 10 18:36:52 CST 2017
     */
    int insertSelective(HaiGoodsAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_attr
     *
     * @mbg.generated Tue Oct 10 18:36:52 CST 2017
     */
    List<HaiGoodsAttr> selectByExample(HaiGoodsAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_attr
     *
     * @mbg.generated Tue Oct 10 18:36:52 CST 2017
     */
    HaiGoodsAttr selectByPrimaryKey(Long goodsAttrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_attr
     *
     * @mbg.generated Tue Oct 10 18:36:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") HaiGoodsAttr record, @Param("example") HaiGoodsAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_attr
     *
     * @mbg.generated Tue Oct 10 18:36:52 CST 2017
     */
    int updateByExample(@Param("record") HaiGoodsAttr record, @Param("example") HaiGoodsAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_attr
     *
     * @mbg.generated Tue Oct 10 18:36:52 CST 2017
     */
    int updateByPrimaryKeySelective(HaiGoodsAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_attr
     *
     * @mbg.generated Tue Oct 10 18:36:52 CST 2017
     */
    int updateByPrimaryKey(HaiGoodsAttr record);
}