package org.ehais.shop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.ehais.shop.model.HaiGoodsAgency;
import org.ehais.shop.model.HaiGoodsAgencyExample;

public interface HaiGoodsAgencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_agency
     *
     * @mbg.generated Sun Aug 13 12:55:47 CST 2017
     */
    @Select("select count(*) from hai_goods_agency where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_agency
     *
     * @mbg.generated Sun Aug 13 12:55:47 CST 2017
     */
    @Select("select count(*) from hai_goods_agency where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_agency
     *
     * @mbg.generated Sun Aug 13 12:55:47 CST 2017
     */
    long countByExample(HaiGoodsAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_agency
     *
     * @mbg.generated Sun Aug 13 12:55:47 CST 2017
     */
    int deleteByExample(HaiGoodsAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_agency
     *
     * @mbg.generated Sun Aug 13 12:55:47 CST 2017
     */
    int deleteByPrimaryKey(Long gaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_agency
     *
     * @mbg.generated Sun Aug 13 12:55:47 CST 2017
     */
    int insert(HaiGoodsAgency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_agency
     *
     * @mbg.generated Sun Aug 13 12:55:47 CST 2017
     */
    int insertSelective(HaiGoodsAgency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_agency
     *
     * @mbg.generated Sun Aug 13 12:55:47 CST 2017
     */
    List<HaiGoodsAgency> selectByExample(HaiGoodsAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_agency
     *
     * @mbg.generated Sun Aug 13 12:55:47 CST 2017
     */
    HaiGoodsAgency selectByPrimaryKey(Long gaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_agency
     *
     * @mbg.generated Sun Aug 13 12:55:47 CST 2017
     */
    int updateByExampleSelective(@Param("record") HaiGoodsAgency record, @Param("example") HaiGoodsAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_agency
     *
     * @mbg.generated Sun Aug 13 12:55:47 CST 2017
     */
    int updateByExample(@Param("record") HaiGoodsAgency record, @Param("example") HaiGoodsAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_agency
     *
     * @mbg.generated Sun Aug 13 12:55:47 CST 2017
     */
    int updateByPrimaryKeySelective(HaiGoodsAgency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_agency
     *
     * @mbg.generated Sun Aug 13 12:55:47 CST 2017
     */
    int updateByPrimaryKey(HaiGoodsAgency record);
}