package org.ehais.shop.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.ehais.shop.model.HaiGoodsGallery;
import org.ehais.shop.model.HaiGoodsGalleryExample;

public interface HaiGoodsGalleryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbggenerated Wed Jun 15 21:41:55 CST 2016
     */
    @ResultMap(value = "BaseResultMap")
    List<HaiGoodsGallery> hai_goods_gallery_list(@Param("store_id") Integer store_id, @Param("start") Integer start, @Param("len") Integer len);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbggenerated Wed Jun 15 21:41:55 CST 2016
     */
    @ResultMap(value = "BaseResultMap")
    List<HaiGoodsGallery> hai_goods_gallery_list_by_example(HaiGoodsGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbggenerated Wed Jun 15 21:41:55 CST 2016
     */
    @ResultMap(value = "BaseResultMap")
    HaiGoodsGallery get_hai_goods_gallery_info(@Param("store_id") Integer store_id, @Param("img_id") Long img_id, @Param("goods_id") Long goods_id);

    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbggenerated Wed Jun 15 21:41:55 CST 2016
     */
    int countByExample(HaiGoodsGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbggenerated Wed Jun 15 21:41:55 CST 2016
     */
    int deleteByExample(HaiGoodsGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbggenerated Wed Jun 15 21:41:55 CST 2016
     */
    int deleteByPrimaryKey(Long imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbggenerated Wed Jun 15 21:41:55 CST 2016
     */
    int insert(HaiGoodsGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbggenerated Wed Jun 15 21:41:55 CST 2016
     */
    int insertSelective(HaiGoodsGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbggenerated Wed Jun 15 21:41:55 CST 2016
     */
    List<HaiGoodsGallery> selectByExample(HaiGoodsGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbggenerated Wed Jun 15 21:41:55 CST 2016
     */
    HaiGoodsGallery selectByPrimaryKey(Long imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbggenerated Wed Jun 15 21:41:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") HaiGoodsGallery record, @Param("example") HaiGoodsGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbggenerated Wed Jun 15 21:41:55 CST 2016
     */
    int updateByExample(@Param("record") HaiGoodsGallery record, @Param("example") HaiGoodsGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbggenerated Wed Jun 15 21:41:55 CST 2016
     */
    int updateByPrimaryKeySelective(HaiGoodsGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbggenerated Wed Jun 15 21:41:55 CST 2016
     */
    int updateByPrimaryKey(HaiGoodsGallery record);
}