package org.ehais.shop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.ehais.shop.model.HaiHotelRoomItem;
import org.ehais.shop.model.HaiHotelRoomItemExample;

public interface HaiHotelRoomItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_hotel_room_item
     *
     * @mbg.generated Wed Jun 20 15:20:03 CST 2018
     */
    @Select("select * from hai_hotel_room_item where hotel_room_item_id = ${hotel_room_item_id} and store_id = ${store_id} ")
    @ResultMap(value = "ResultMapWithBLOBs") //BaseResultMap  ResultMapWithBLOBs
    HaiHotelRoomItem get_hai_hotel_room_item_info(@Param("hotel_room_item_id") Integer hotel_room_item_id, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_hotel_room_item
     *
     * @mbg.generated Wed Jun 20 15:20:03 CST 2018
     */
    @Select("select count(*) from hai_hotel_room_item where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_hotel_room_item
     *
     * @mbg.generated Wed Jun 20 15:20:03 CST 2018
     */
    @Select("select count(*) from hai_hotel_room_item where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_hotel_room_item
     *
     * @mbg.generated Wed Jun 20 15:20:03 CST 2018
     */
    long countByExample(HaiHotelRoomItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_hotel_room_item
     *
     * @mbg.generated Wed Jun 20 15:20:03 CST 2018
     */
    int deleteByExample(HaiHotelRoomItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_hotel_room_item
     *
     * @mbg.generated Wed Jun 20 15:20:03 CST 2018
     */
    int deleteByPrimaryKey(Integer hotelRoomItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_hotel_room_item
     *
     * @mbg.generated Wed Jun 20 15:20:03 CST 2018
     */
    int insert(HaiHotelRoomItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_hotel_room_item
     *
     * @mbg.generated Wed Jun 20 15:20:03 CST 2018
     */
    int insertSelective(HaiHotelRoomItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_hotel_room_item
     *
     * @mbg.generated Wed Jun 20 15:20:03 CST 2018
     */
    List<HaiHotelRoomItem> selectByExample(HaiHotelRoomItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_hotel_room_item
     *
     * @mbg.generated Wed Jun 20 15:20:03 CST 2018
     */
    HaiHotelRoomItem selectByPrimaryKey(Integer hotelRoomItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_hotel_room_item
     *
     * @mbg.generated Wed Jun 20 15:20:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") HaiHotelRoomItem record, @Param("example") HaiHotelRoomItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_hotel_room_item
     *
     * @mbg.generated Wed Jun 20 15:20:03 CST 2018
     */
    int updateByExample(@Param("record") HaiHotelRoomItem record, @Param("example") HaiHotelRoomItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_hotel_room_item
     *
     * @mbg.generated Wed Jun 20 15:20:03 CST 2018
     */
    int updateByPrimaryKeySelective(HaiHotelRoomItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_hotel_room_item
     *
     * @mbg.generated Wed Jun 20 15:20:03 CST 2018
     */
    int updateByPrimaryKey(HaiHotelRoomItem record);
}