package org.ehais.shop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.ehais.shop.model.HaiPayment;
import org.ehais.shop.model.HaiPaymentExample;

public interface HaiPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_payment
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    @Select("select * from hai_payment where pay_id = ${pay_id} and store_id = ${store_id} ")
    @ResultMap(value = "ResultMapWithBLOBs") //BaseResultMap  ResultMapWithBLOBs
    HaiPayment get_hai_payment_info(@Param("pay_id") Integer pay_id, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_payment
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    @Select("select count(*) from hai_payment where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_payment
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    @Select("select count(*) from hai_payment where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_payment
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    long countByExample(HaiPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_payment
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int deleteByExample(HaiPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_payment
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int deleteByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_payment
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int insert(HaiPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_payment
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int insertSelective(HaiPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_payment
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    List<HaiPayment> selectByExample(HaiPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_payment
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    HaiPayment selectByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_payment
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") HaiPayment record, @Param("example") HaiPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_payment
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int updateByExample(@Param("record") HaiPayment record, @Param("example") HaiPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_payment
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int updateByPrimaryKeySelective(HaiPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_payment
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int updateByPrimaryKey(HaiPayment record);
}