package org.ehais.shop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.ehais.shop.model.HaiProperty;
import org.ehais.shop.model.HaiPropertyExample;

public interface HaiPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_property
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    @Select("select * from hai_property where property_id = ${property_id} and store_id = ${store_id} ")
    @ResultMap(value = "ResultMapWithBLOBs") //BaseResultMap  ResultMapWithBLOBs
    HaiProperty get_hai_property_info(@Param("property_id") Integer property_id, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_property
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    @Select("select count(*) from hai_property where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_property
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    @Select("select count(*) from hai_property where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_property
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    long countByExample(HaiPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_property
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int deleteByExample(HaiPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_property
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int deleteByPrimaryKey(Integer propertyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_property
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int insert(HaiProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_property
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int insertSelective(HaiProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_property
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    List<HaiProperty> selectByExampleWithBLOBs(HaiPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_property
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    List<HaiProperty> selectByExample(HaiPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_property
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    HaiProperty selectByPrimaryKey(Integer propertyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_property
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") HaiProperty record, @Param("example") HaiPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_property
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") HaiProperty record, @Param("example") HaiPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_property
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int updateByExample(@Param("record") HaiProperty record, @Param("example") HaiPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_property
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int updateByPrimaryKeySelective(HaiProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_property
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(HaiProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_property
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    int updateByPrimaryKey(HaiProperty record);
}