package org.ehais.shop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.ehais.shop.model.HaiSearchHistory;
import org.ehais.shop.model.HaiSearchHistoryExample;

public interface HaiSearchHistoryMapper {
	
	/**
	 * 清空用户的搜索记录
	 * @param user_id
	 * @return
	 */
	@Update("update hai_search_history set is_valid = 0 where classify = 'user' and user_id = #{user_id}")
	int clear_keyword_history(@Param("user_id") Long user_id);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_search_history
     *
     * @mbg.generated Mon Nov 13 21:48:58 CST 2017
     */
    @Select("select count(*) from hai_search_history where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_search_history
     *
     * @mbg.generated Mon Nov 13 21:48:58 CST 2017
     */
    @Select("select count(*) from hai_search_history where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_search_history
     *
     * @mbg.generated Mon Nov 13 21:48:58 CST 2017
     */
    long countByExample(HaiSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_search_history
     *
     * @mbg.generated Mon Nov 13 21:48:58 CST 2017
     */
    int deleteByExample(HaiSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_search_history
     *
     * @mbg.generated Mon Nov 13 21:48:58 CST 2017
     */
    int deleteByPrimaryKey(Long historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_search_history
     *
     * @mbg.generated Mon Nov 13 21:48:58 CST 2017
     */
    int insert(HaiSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_search_history
     *
     * @mbg.generated Mon Nov 13 21:48:58 CST 2017
     */
    int insertSelective(HaiSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_search_history
     *
     * @mbg.generated Mon Nov 13 21:48:58 CST 2017
     */
    List<HaiSearchHistory> selectByExample(HaiSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_search_history
     *
     * @mbg.generated Mon Nov 13 21:48:58 CST 2017
     */
    HaiSearchHistory selectByPrimaryKey(Long historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_search_history
     *
     * @mbg.generated Mon Nov 13 21:48:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") HaiSearchHistory record, @Param("example") HaiSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_search_history
     *
     * @mbg.generated Mon Nov 13 21:48:58 CST 2017
     */
    int updateByExample(@Param("record") HaiSearchHistory record, @Param("example") HaiSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_search_history
     *
     * @mbg.generated Mon Nov 13 21:48:58 CST 2017
     */
    int updateByPrimaryKeySelective(HaiSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_search_history
     *
     * @mbg.generated Mon Nov 13 21:48:58 CST 2017
     */
    int updateByPrimaryKey(HaiSearchHistory record);
}