package org.ehais.shop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.ehais.shop.model.HaiUsersRelation;
import org.ehais.shop.model.HaiUsersRelationExample;

public interface HaiUsersRelationMapper {
	
	
	@Select("select * from hai_users_relation where first_user_id = #{user_id} or second_user_id = #{user_id} or third_user_id = #{user_id} order by user_id desc limit #{start},#{end}")
	@ResultMap(value = "BaseResultMap")
	List<HaiUsersRelation> selectUsersRelation(
			@Param("user_id") Long user_id,
			@Param("start") Integer start,
			@Param("end") Integer end);
	
	
	@Select("select count(*) from hai_users_relation where first_user_id = #{user_id} or second_user_id = #{user_id} or third_user_id = #{user_id} ")
	long countUsersRelation(@Param("user_id") Long user_id);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_users_relation
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    @Select("select count(*) from hai_users_relation where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_users_relation
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    @Select("select count(*) from hai_users_relation where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_users_relation
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    long countByExample(HaiUsersRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_users_relation
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    int deleteByExample(HaiUsersRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_users_relation
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_users_relation
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    int insert(HaiUsersRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_users_relation
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    int insertSelective(HaiUsersRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_users_relation
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    List<HaiUsersRelation> selectByExample(HaiUsersRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_users_relation
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    HaiUsersRelation selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_users_relation
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    int updateByExampleSelective(@Param("record") HaiUsersRelation record, @Param("example") HaiUsersRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_users_relation
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    int updateByExample(@Param("record") HaiUsersRelation record, @Param("example") HaiUsersRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_users_relation
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    int updateByPrimaryKeySelective(HaiUsersRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_users_relation
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    int updateByPrimaryKey(HaiUsersRelation record);
}