package org.ehais.shop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.ehais.shop.model.HaiUnit;
import org.ehais.shop.model.HaiUnitExample;

public interface HaiUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_unit
     *
     * @mbg.generated Mon Jun 11 10:34:38 CST 2018
     */
    @Select("select count(*) from hai_unit where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_unit
     *
     * @mbg.generated Mon Jun 11 10:34:38 CST 2018
     */
    @Select("select count(*) from hai_unit where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_unit
     *
     * @mbg.generated Mon Jun 11 10:34:38 CST 2018
     */
    long countByExample(HaiUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_unit
     *
     * @mbg.generated Mon Jun 11 10:34:38 CST 2018
     */
    int deleteByExample(HaiUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_unit
     *
     * @mbg.generated Mon Jun 11 10:34:38 CST 2018
     */
    int deleteByPrimaryKey(Integer unitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_unit
     *
     * @mbg.generated Mon Jun 11 10:34:38 CST 2018
     */
    int insert(HaiUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_unit
     *
     * @mbg.generated Mon Jun 11 10:34:38 CST 2018
     */
    int insertSelective(HaiUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_unit
     *
     * @mbg.generated Mon Jun 11 10:34:38 CST 2018
     */
    List<HaiUnit> selectByExample(HaiUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_unit
     *
     * @mbg.generated Mon Jun 11 10:34:38 CST 2018
     */
    HaiUnit selectByPrimaryKey(Integer unitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_unit
     *
     * @mbg.generated Mon Jun 11 10:34:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") HaiUnit record, @Param("example") HaiUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_unit
     *
     * @mbg.generated Mon Jun 11 10:34:38 CST 2018
     */
    int updateByExample(@Param("record") HaiUnit record, @Param("example") HaiUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_unit
     *
     * @mbg.generated Mon Jun 11 10:34:38 CST 2018
     */
    int updateByPrimaryKeySelective(HaiUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_unit
     *
     * @mbg.generated Mon Jun 11 10:34:38 CST 2018
     */
    int updateByPrimaryKey(HaiUnit record);
}