package org.ehais.epublic.mapper.weixin;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.ehais.epublic.model.weixin.WxTransfersResult;
import org.ehais.epublic.model.weixin.WxTransfersResultExample;

public interface WxTransfersResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_transfers_result
     *
     * @mbg.generated Mon May 28 09:27:35 CST 2018
     */
    @Select("select count(*) from wx_transfers_result where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_transfers_result
     *
     * @mbg.generated Mon May 28 09:27:35 CST 2018
     */
    @Select("select count(*) from wx_transfers_result where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_transfers_result
     *
     * @mbg.generated Mon May 28 09:27:35 CST 2018
     */
    long countByExample(WxTransfersResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_transfers_result
     *
     * @mbg.generated Mon May 28 09:27:35 CST 2018
     */
    int deleteByExample(WxTransfersResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_transfers_result
     *
     * @mbg.generated Mon May 28 09:27:35 CST 2018
     */
    int deleteByPrimaryKey(Integer transfersResultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_transfers_result
     *
     * @mbg.generated Mon May 28 09:27:35 CST 2018
     */
    int insert(WxTransfersResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_transfers_result
     *
     * @mbg.generated Mon May 28 09:27:35 CST 2018
     */
    int insertSelective(WxTransfersResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_transfers_result
     *
     * @mbg.generated Mon May 28 09:27:35 CST 2018
     */
    List<WxTransfersResult> selectByExample(WxTransfersResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_transfers_result
     *
     * @mbg.generated Mon May 28 09:27:35 CST 2018
     */
    WxTransfersResult selectByPrimaryKey(Integer transfersResultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_transfers_result
     *
     * @mbg.generated Mon May 28 09:27:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") WxTransfersResult record, @Param("example") WxTransfersResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_transfers_result
     *
     * @mbg.generated Mon May 28 09:27:35 CST 2018
     */
    int updateByExample(@Param("record") WxTransfersResult record, @Param("example") WxTransfersResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_transfers_result
     *
     * @mbg.generated Mon May 28 09:27:35 CST 2018
     */
    int updateByPrimaryKeySelective(WxTransfersResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_transfers_result
     *
     * @mbg.generated Mon May 28 09:27:35 CST 2018
     */
    int updateByPrimaryKey(WxTransfersResult record);
}