package org.ehais.epublic.mapper.weixin;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.ehais.epublic.model.weixin.WxUnifiedorder;
import org.ehais.epublic.model.weixin.WxUnifiedorderExample;

public interface WxUnifiedorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_unifiedorder
     *
     * @mbg.generated Mon Aug 28 19:23:05 CST 2017
     */
    @Select("select count(*) from wx_unifiedorder where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_unifiedorder
     *
     * @mbg.generated Mon Aug 28 19:23:05 CST 2017
     */
    @Select("select count(*) from wx_unifiedorder where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_unifiedorder
     *
     * @mbg.generated Mon Aug 28 19:23:05 CST 2017
     */
    long countByExample(WxUnifiedorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_unifiedorder
     *
     * @mbg.generated Mon Aug 28 19:23:05 CST 2017
     */
    int deleteByExample(WxUnifiedorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_unifiedorder
     *
     * @mbg.generated Mon Aug 28 19:23:05 CST 2017
     */
    int deleteByPrimaryKey(Integer wxOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_unifiedorder
     *
     * @mbg.generated Mon Aug 28 19:23:05 CST 2017
     */
    int insert(WxUnifiedorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_unifiedorder
     *
     * @mbg.generated Mon Aug 28 19:23:05 CST 2017
     */
    int insertSelective(WxUnifiedorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_unifiedorder
     *
     * @mbg.generated Mon Aug 28 19:23:05 CST 2017
     */
    List<WxUnifiedorder> selectByExample(WxUnifiedorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_unifiedorder
     *
     * @mbg.generated Mon Aug 28 19:23:05 CST 2017
     */
    WxUnifiedorder selectByPrimaryKey(Integer wxOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_unifiedorder
     *
     * @mbg.generated Mon Aug 28 19:23:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") WxUnifiedorder record, @Param("example") WxUnifiedorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_unifiedorder
     *
     * @mbg.generated Mon Aug 28 19:23:05 CST 2017
     */
    int updateByExample(@Param("record") WxUnifiedorder record, @Param("example") WxUnifiedorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_unifiedorder
     *
     * @mbg.generated Mon Aug 28 19:23:05 CST 2017
     */
    int updateByPrimaryKeySelective(WxUnifiedorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_unifiedorder
     *
     * @mbg.generated Mon Aug 28 19:23:05 CST 2017
     */
    int updateByPrimaryKey(WxUnifiedorder record);
}