package org.ehais.epublic.model.alipay;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class AlipayNotifyUrl implements Serializable {

    private Long id;

    private Date notifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.notify_type
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private String notifyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.notify_id
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private String notifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.sign_type
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private String signType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.sign
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.out_trade_no
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.trade_no
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.subject
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.total_fee
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private Double totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.payment_type
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private String paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.body
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.trade_status
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private String tradeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.gmt_create
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.gmt_payment
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private Date gmtPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.gmt_close
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private Date gmtClose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.seller_email
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private String sellerEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.buyer_email
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private String buyerEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.seller_id
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private String sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.buyer_id
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private String buyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.price
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.quantity
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.discount
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private Float discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.is_total_fee_adjus
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private String isTotalFeeAdjus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.use_coupon
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private String useCoupon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_notify_url.create_date
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alipay_notify_url
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.id
     *
     * @return the value of alipay_notify_url.id
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.id
     *
     * @param id the value for alipay_notify_url.id
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.notify_time
     *
     * @return the value of alipay_notify_url.notify_time
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public Date getNotifyTime() {
        return notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.notify_time
     *
     * @param notifyTime the value for alipay_notify_url.notify_time
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setNotifyTime(Date notifyTime) {
        this.notifyTime = notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.notify_type
     *
     * @return the value of alipay_notify_url.notify_type
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public String getNotifyType() {
        return notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.notify_type
     *
     * @param notifyType the value for alipay_notify_url.notify_type
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setNotifyType(String notifyType) {
        this.notifyType = notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.notify_id
     *
     * @return the value of alipay_notify_url.notify_id
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public String getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.notify_id
     *
     * @param notifyId the value for alipay_notify_url.notify_id
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setNotifyId(String notifyId) {
        this.notifyId = notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.sign_type
     *
     * @return the value of alipay_notify_url.sign_type
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public String getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.sign_type
     *
     * @param signType the value for alipay_notify_url.sign_type
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setSignType(String signType) {
        this.signType = signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.sign
     *
     * @return the value of alipay_notify_url.sign
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.sign
     *
     * @param sign the value for alipay_notify_url.sign
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setSign(String sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.out_trade_no
     *
     * @return the value of alipay_notify_url.out_trade_no
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.out_trade_no
     *
     * @param outTradeNo the value for alipay_notify_url.out_trade_no
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.trade_no
     *
     * @return the value of alipay_notify_url.trade_no
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.trade_no
     *
     * @param tradeNo the value for alipay_notify_url.trade_no
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.subject
     *
     * @return the value of alipay_notify_url.subject
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.subject
     *
     * @param subject the value for alipay_notify_url.subject
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.total_fee
     *
     * @return the value of alipay_notify_url.total_fee
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public Double getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.total_fee
     *
     * @param totalFee the value for alipay_notify_url.total_fee
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setTotalFee(Double totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.payment_type
     *
     * @return the value of alipay_notify_url.payment_type
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.payment_type
     *
     * @param paymentType the value for alipay_notify_url.payment_type
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.body
     *
     * @return the value of alipay_notify_url.body
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.body
     *
     * @param body the value for alipay_notify_url.body
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.trade_status
     *
     * @return the value of alipay_notify_url.trade_status
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public String getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.trade_status
     *
     * @param tradeStatus the value for alipay_notify_url.trade_status
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setTradeStatus(String tradeStatus) {
        this.tradeStatus = tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.gmt_create
     *
     * @return the value of alipay_notify_url.gmt_create
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.gmt_create
     *
     * @param gmtCreate the value for alipay_notify_url.gmt_create
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.gmt_payment
     *
     * @return the value of alipay_notify_url.gmt_payment
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public Date getGmtPayment() {
        return gmtPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.gmt_payment
     *
     * @param gmtPayment the value for alipay_notify_url.gmt_payment
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setGmtPayment(Date gmtPayment) {
        this.gmtPayment = gmtPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.gmt_close
     *
     * @return the value of alipay_notify_url.gmt_close
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public Date getGmtClose() {
        return gmtClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.gmt_close
     *
     * @param gmtClose the value for alipay_notify_url.gmt_close
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setGmtClose(Date gmtClose) {
        this.gmtClose = gmtClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.seller_email
     *
     * @return the value of alipay_notify_url.seller_email
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public String getSellerEmail() {
        return sellerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.seller_email
     *
     * @param sellerEmail the value for alipay_notify_url.seller_email
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setSellerEmail(String sellerEmail) {
        this.sellerEmail = sellerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.buyer_email
     *
     * @return the value of alipay_notify_url.buyer_email
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public String getBuyerEmail() {
        return buyerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.buyer_email
     *
     * @param buyerEmail the value for alipay_notify_url.buyer_email
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setBuyerEmail(String buyerEmail) {
        this.buyerEmail = buyerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.seller_id
     *
     * @return the value of alipay_notify_url.seller_id
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.seller_id
     *
     * @param sellerId the value for alipay_notify_url.seller_id
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.buyer_id
     *
     * @return the value of alipay_notify_url.buyer_id
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public String getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.buyer_id
     *
     * @param buyerId the value for alipay_notify_url.buyer_id
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setBuyerId(String buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.price
     *
     * @return the value of alipay_notify_url.price
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.price
     *
     * @param price the value for alipay_notify_url.price
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.quantity
     *
     * @return the value of alipay_notify_url.quantity
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.quantity
     *
     * @param quantity the value for alipay_notify_url.quantity
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.discount
     *
     * @return the value of alipay_notify_url.discount
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public Float getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.discount
     *
     * @param discount the value for alipay_notify_url.discount
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setDiscount(Float discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.is_total_fee_adjus
     *
     * @return the value of alipay_notify_url.is_total_fee_adjus
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public String getIsTotalFeeAdjus() {
        return isTotalFeeAdjus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.is_total_fee_adjus
     *
     * @param isTotalFeeAdjus the value for alipay_notify_url.is_total_fee_adjus
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setIsTotalFeeAdjus(String isTotalFeeAdjus) {
        this.isTotalFeeAdjus = isTotalFeeAdjus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.use_coupon
     *
     * @return the value of alipay_notify_url.use_coupon
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public String getUseCoupon() {
        return useCoupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.use_coupon
     *
     * @param useCoupon the value for alipay_notify_url.use_coupon
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setUseCoupon(String useCoupon) {
        this.useCoupon = useCoupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_notify_url.create_date
     *
     * @return the value of alipay_notify_url.create_date
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_notify_url.create_date
     *
     * @param createDate the value for alipay_notify_url.create_date
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

	public void AlipayNotifyUrlByModel(AlipayNotifyModel model) {
		
		this.notifyTime = model.getNotify_time();
		this.notifyType = model.getNotify_type();
		this.notifyId = model.getNotify_id();
		this.signType = model.getSign_type();
		this.sign = model.getSign();
		this.outTradeNo = model.getOut_trade_no();
		this.tradeNo = model.getTrade_no();
		this.subject = model.getSubject();
		this.totalFee = model.getTotal_fee();
		this.paymentType = model.getPayment_type();
		this.body = model.getBody();
		this.tradeStatus = model.getTrade_status();
		this.gmtCreate = model.getGmt_create();
		this.gmtPayment = model.getGmt_payment();
		this.gmtClose = model.getGmt_close();
		this.sellerEmail = model.getSeller_email();
		this.buyerEmail = model.getBuyer_email();
		this.sellerId = model.getSeller_id();
		this.buyerId = model.getBuyer_id();
		this.price = model.getPrice();
		this.quantity = model.getQuantity();
		this.discount = model.getDiscount();
		this.isTotalFeeAdjus = model.getIs_total_fee_adjus();
		this.useCoupon = model.getUse_coupon();
		this.createDate = new Date();
	}
    
    
    
}