package org.ehais.shop.model;

import java.io.Serializable;

public class HaiAdPosition implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_ad_position.position_id
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    private Integer positionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_ad_position.position_code
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    private String positionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_ad_position.position_name
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    private String positionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_ad_position.ad_width
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    private Integer adWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_ad_position.ad_height
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    private Integer adHeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_ad_position.position_desc
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    private String positionDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_ad_position.store_id
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_ad_position.agency_id
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    private Integer agencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_ad_position.partner_id
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    private Integer partnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_ad_position.is_void
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    private Integer isVoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_ad_position.position_style
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    private String positionStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hai_ad_position
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_ad_position.position_id
     *
     * @return the value of hai_ad_position.position_id
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_ad_position.position_id
     *
     * @param positionId the value for hai_ad_position.position_id
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_ad_position.position_code
     *
     * @return the value of hai_ad_position.position_code
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public String getPositionCode() {
        return positionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_ad_position.position_code
     *
     * @param positionCode the value for hai_ad_position.position_code
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public void setPositionCode(String positionCode) {
        this.positionCode = positionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_ad_position.position_name
     *
     * @return the value of hai_ad_position.position_name
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_ad_position.position_name
     *
     * @param positionName the value for hai_ad_position.position_name
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_ad_position.ad_width
     *
     * @return the value of hai_ad_position.ad_width
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public Integer getAdWidth() {
        return adWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_ad_position.ad_width
     *
     * @param adWidth the value for hai_ad_position.ad_width
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public void setAdWidth(Integer adWidth) {
        this.adWidth = adWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_ad_position.ad_height
     *
     * @return the value of hai_ad_position.ad_height
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public Integer getAdHeight() {
        return adHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_ad_position.ad_height
     *
     * @param adHeight the value for hai_ad_position.ad_height
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public void setAdHeight(Integer adHeight) {
        this.adHeight = adHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_ad_position.position_desc
     *
     * @return the value of hai_ad_position.position_desc
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public String getPositionDesc() {
        return positionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_ad_position.position_desc
     *
     * @param positionDesc the value for hai_ad_position.position_desc
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public void setPositionDesc(String positionDesc) {
        this.positionDesc = positionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_ad_position.store_id
     *
     * @return the value of hai_ad_position.store_id
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_ad_position.store_id
     *
     * @param storeId the value for hai_ad_position.store_id
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_ad_position.agency_id
     *
     * @return the value of hai_ad_position.agency_id
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public Integer getAgencyId() {
        return agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_ad_position.agency_id
     *
     * @param agencyId the value for hai_ad_position.agency_id
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public void setAgencyId(Integer agencyId) {
        this.agencyId = agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_ad_position.partner_id
     *
     * @return the value of hai_ad_position.partner_id
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public Integer getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_ad_position.partner_id
     *
     * @param partnerId the value for hai_ad_position.partner_id
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public void setPartnerId(Integer partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_ad_position.is_void
     *
     * @return the value of hai_ad_position.is_void
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public Integer getIsVoid() {
        return isVoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_ad_position.is_void
     *
     * @param isVoid the value for hai_ad_position.is_void
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public void setIsVoid(Integer isVoid) {
        this.isVoid = isVoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_ad_position.position_style
     *
     * @return the value of hai_ad_position.position_style
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public String getPositionStyle() {
        return positionStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_ad_position.position_style
     *
     * @param positionStyle the value for hai_ad_position.position_style
     *
     * @mbg.generated Tue Sep 12 17:15:27 CST 2017
     */
    public void setPositionStyle(String positionStyle) {
        this.positionStyle = positionStyle;
    }
}