package org.ehais.shop.model;

import java.io.Serializable;

public class HaiBusinessLinkman implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_business_linkman.business_linkman_id
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    private Integer businessLinkmanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_business_linkman.business_id
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    private Integer businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_business_linkman.linkman
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    private String linkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_business_linkman.phone
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_business_linkman.tel
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_business_linkman.fax
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_business_linkman.email
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_business_linkman.address
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_business_linkman.is_void
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    private Byte isVoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_business_linkman.intro
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_business_linkman.qq
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_business_linkman.weixin
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    private String weixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hai_business_linkman
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_business_linkman.business_linkman_id
     *
     * @return the value of hai_business_linkman.business_linkman_id
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public Integer getBusinessLinkmanId() {
        return businessLinkmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_business_linkman.business_linkman_id
     *
     * @param businessLinkmanId the value for hai_business_linkman.business_linkman_id
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public void setBusinessLinkmanId(Integer businessLinkmanId) {
        this.businessLinkmanId = businessLinkmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_business_linkman.business_id
     *
     * @return the value of hai_business_linkman.business_id
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_business_linkman.business_id
     *
     * @param businessId the value for hai_business_linkman.business_id
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_business_linkman.linkman
     *
     * @return the value of hai_business_linkman.linkman
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_business_linkman.linkman
     *
     * @param linkman the value for hai_business_linkman.linkman
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_business_linkman.phone
     *
     * @return the value of hai_business_linkman.phone
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_business_linkman.phone
     *
     * @param phone the value for hai_business_linkman.phone
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_business_linkman.tel
     *
     * @return the value of hai_business_linkman.tel
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_business_linkman.tel
     *
     * @param tel the value for hai_business_linkman.tel
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_business_linkman.fax
     *
     * @return the value of hai_business_linkman.fax
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_business_linkman.fax
     *
     * @param fax the value for hai_business_linkman.fax
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_business_linkman.email
     *
     * @return the value of hai_business_linkman.email
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_business_linkman.email
     *
     * @param email the value for hai_business_linkman.email
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_business_linkman.address
     *
     * @return the value of hai_business_linkman.address
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_business_linkman.address
     *
     * @param address the value for hai_business_linkman.address
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_business_linkman.is_void
     *
     * @return the value of hai_business_linkman.is_void
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public Byte getIsVoid() {
        return isVoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_business_linkman.is_void
     *
     * @param isVoid the value for hai_business_linkman.is_void
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public void setIsVoid(Byte isVoid) {
        this.isVoid = isVoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_business_linkman.intro
     *
     * @return the value of hai_business_linkman.intro
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_business_linkman.intro
     *
     * @param intro the value for hai_business_linkman.intro
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_business_linkman.qq
     *
     * @return the value of hai_business_linkman.qq
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_business_linkman.qq
     *
     * @param qq the value for hai_business_linkman.qq
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_business_linkman.weixin
     *
     * @return the value of hai_business_linkman.weixin
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_business_linkman.weixin
     *
     * @param weixin the value for hai_business_linkman.weixin
     *
     * @mbg.generated Fri Jun 22 12:42:58 CST 2018
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin;
    }
}