package org.ehais.shop.model;

import java.io.Serializable;
import java.util.Date;

public class HaiIncome implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_income.income_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private Integer incomeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_income.income_code
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private String incomeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_income.income_name
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private String incomeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_income.store_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_income.create_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_income.update_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_income.last_update_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_income.create_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private Long createAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_income.update_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private Long updateAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_income.last_update_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private Long lastUpdateAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_income.remark
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hai_income
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_income.income_id
     *
     * @return the value of hai_income.income_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public Integer getIncomeId() {
        return incomeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_income.income_id
     *
     * @param incomeId the value for hai_income.income_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setIncomeId(Integer incomeId) {
        this.incomeId = incomeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_income.income_code
     *
     * @return the value of hai_income.income_code
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public String getIncomeCode() {
        return incomeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_income.income_code
     *
     * @param incomeCode the value for hai_income.income_code
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setIncomeCode(String incomeCode) {
        this.incomeCode = incomeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_income.income_name
     *
     * @return the value of hai_income.income_name
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public String getIncomeName() {
        return incomeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_income.income_name
     *
     * @param incomeName the value for hai_income.income_name
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setIncomeName(String incomeName) {
        this.incomeName = incomeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_income.store_id
     *
     * @return the value of hai_income.store_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_income.store_id
     *
     * @param storeId the value for hai_income.store_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_income.create_date
     *
     * @return the value of hai_income.create_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_income.create_date
     *
     * @param createDate the value for hai_income.create_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_income.update_date
     *
     * @return the value of hai_income.update_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_income.update_date
     *
     * @param updateDate the value for hai_income.update_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_income.last_update_date
     *
     * @return the value of hai_income.last_update_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_income.last_update_date
     *
     * @param lastUpdateDate the value for hai_income.last_update_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_income.create_admin_id
     *
     * @return the value of hai_income.create_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public Long getCreateAdminId() {
        return createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_income.create_admin_id
     *
     * @param createAdminId the value for hai_income.create_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setCreateAdminId(Long createAdminId) {
        this.createAdminId = createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_income.update_admin_id
     *
     * @return the value of hai_income.update_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public Long getUpdateAdminId() {
        return updateAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_income.update_admin_id
     *
     * @param updateAdminId the value for hai_income.update_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setUpdateAdminId(Long updateAdminId) {
        this.updateAdminId = updateAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_income.last_update_admin_id
     *
     * @return the value of hai_income.last_update_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public Long getLastUpdateAdminId() {
        return lastUpdateAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_income.last_update_admin_id
     *
     * @param lastUpdateAdminId the value for hai_income.last_update_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setLastUpdateAdminId(Long lastUpdateAdminId) {
        this.lastUpdateAdminId = lastUpdateAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_income.remark
     *
     * @return the value of hai_income.remark
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_income.remark
     *
     * @param remark the value for hai_income.remark
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}