package org.ehais.shop.model;

import java.io.Serializable;

public class HaiOrderGoods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.rec_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private Long recId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.order_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.sub_order_sn
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private String subOrderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.goods_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.goods_name
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.goods_sn
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private String goodsSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.product_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.goods_number
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private Integer goodsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.market_price
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private Integer marketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.goods_price
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private Integer goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.goods_thumb
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private String goodsThumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.send_number
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private Integer sendNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.is_real
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private Boolean isReal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.extension_code
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private String extensionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.parent_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.is_gift
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private Short isGift;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.goods_attr_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private String goodsAttrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.store_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.agency_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private Integer agencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.article_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.seller_user_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private Long sellerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_order_goods.goods_attr
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private String goodsAttr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hai_order_goods
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.rec_id
     *
     * @return the value of hai_order_goods.rec_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public Long getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.rec_id
     *
     * @param recId the value for hai_order_goods.rec_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setRecId(Long recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.order_id
     *
     * @return the value of hai_order_goods.order_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.order_id
     *
     * @param orderId the value for hai_order_goods.order_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.sub_order_sn
     *
     * @return the value of hai_order_goods.sub_order_sn
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public String getSubOrderSn() {
        return subOrderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.sub_order_sn
     *
     * @param subOrderSn the value for hai_order_goods.sub_order_sn
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setSubOrderSn(String subOrderSn) {
        this.subOrderSn = subOrderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.goods_id
     *
     * @return the value of hai_order_goods.goods_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.goods_id
     *
     * @param goodsId the value for hai_order_goods.goods_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.goods_name
     *
     * @return the value of hai_order_goods.goods_name
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.goods_name
     *
     * @param goodsName the value for hai_order_goods.goods_name
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.goods_sn
     *
     * @return the value of hai_order_goods.goods_sn
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.goods_sn
     *
     * @param goodsSn the value for hai_order_goods.goods_sn
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.product_id
     *
     * @return the value of hai_order_goods.product_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.product_id
     *
     * @param productId the value for hai_order_goods.product_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.goods_number
     *
     * @return the value of hai_order_goods.goods_number
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public Integer getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.goods_number
     *
     * @param goodsNumber the value for hai_order_goods.goods_number
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setGoodsNumber(Integer goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.market_price
     *
     * @return the value of hai_order_goods.market_price
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public Integer getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.market_price
     *
     * @param marketPrice the value for hai_order_goods.market_price
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setMarketPrice(Integer marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.goods_price
     *
     * @return the value of hai_order_goods.goods_price
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public Integer getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.goods_price
     *
     * @param goodsPrice the value for hai_order_goods.goods_price
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setGoodsPrice(Integer goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.goods_thumb
     *
     * @return the value of hai_order_goods.goods_thumb
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public String getGoodsThumb() {
        return goodsThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.goods_thumb
     *
     * @param goodsThumb the value for hai_order_goods.goods_thumb
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setGoodsThumb(String goodsThumb) {
        this.goodsThumb = goodsThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.send_number
     *
     * @return the value of hai_order_goods.send_number
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public Integer getSendNumber() {
        return sendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.send_number
     *
     * @param sendNumber the value for hai_order_goods.send_number
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setSendNumber(Integer sendNumber) {
        this.sendNumber = sendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.is_real
     *
     * @return the value of hai_order_goods.is_real
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public Boolean getIsReal() {
        return isReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.is_real
     *
     * @param isReal the value for hai_order_goods.is_real
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setIsReal(Boolean isReal) {
        this.isReal = isReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.extension_code
     *
     * @return the value of hai_order_goods.extension_code
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public String getExtensionCode() {
        return extensionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.extension_code
     *
     * @param extensionCode the value for hai_order_goods.extension_code
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setExtensionCode(String extensionCode) {
        this.extensionCode = extensionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.parent_id
     *
     * @return the value of hai_order_goods.parent_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.parent_id
     *
     * @param parentId the value for hai_order_goods.parent_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.is_gift
     *
     * @return the value of hai_order_goods.is_gift
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public Short getIsGift() {
        return isGift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.is_gift
     *
     * @param isGift the value for hai_order_goods.is_gift
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setIsGift(Short isGift) {
        this.isGift = isGift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.goods_attr_id
     *
     * @return the value of hai_order_goods.goods_attr_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public String getGoodsAttrId() {
        return goodsAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.goods_attr_id
     *
     * @param goodsAttrId the value for hai_order_goods.goods_attr_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setGoodsAttrId(String goodsAttrId) {
        this.goodsAttrId = goodsAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.store_id
     *
     * @return the value of hai_order_goods.store_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.store_id
     *
     * @param storeId the value for hai_order_goods.store_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.agency_id
     *
     * @return the value of hai_order_goods.agency_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public Integer getAgencyId() {
        return agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.agency_id
     *
     * @param agencyId the value for hai_order_goods.agency_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setAgencyId(Integer agencyId) {
        this.agencyId = agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.article_id
     *
     * @return the value of hai_order_goods.article_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.article_id
     *
     * @param articleId the value for hai_order_goods.article_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.seller_user_id
     *
     * @return the value of hai_order_goods.seller_user_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public Long getSellerUserId() {
        return sellerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.seller_user_id
     *
     * @param sellerUserId the value for hai_order_goods.seller_user_id
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setSellerUserId(Long sellerUserId) {
        this.sellerUserId = sellerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_order_goods.goods_attr
     *
     * @return the value of hai_order_goods.goods_attr
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public String getGoodsAttr() {
        return goodsAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_order_goods.goods_attr
     *
     * @param goodsAttr the value for hai_order_goods.goods_attr
     *
     * @mbg.generated Wed Aug 30 09:48:17 CST 2017
     */
    public void setGoodsAttr(String goodsAttr) {
        this.goodsAttr = goodsAttr;
    }
}