package org.ehais.shop.model;

import java.io.Serializable;

public class HaiUsersRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_users_relation.user_id
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_users_relation.first_user_id
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    private Long firstUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_users_relation.second_user_id
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    private Long secondUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_users_relation.third_user_id
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    private Long thirdUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hai_users_relation
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_users_relation.user_id
     *
     * @return the value of hai_users_relation.user_id
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_users_relation.user_id
     *
     * @param userId the value for hai_users_relation.user_id
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_users_relation.first_user_id
     *
     * @return the value of hai_users_relation.first_user_id
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    public Long getFirstUserId() {
        return firstUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_users_relation.first_user_id
     *
     * @param firstUserId the value for hai_users_relation.first_user_id
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    public void setFirstUserId(Long firstUserId) {
        this.firstUserId = firstUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_users_relation.second_user_id
     *
     * @return the value of hai_users_relation.second_user_id
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    public Long getSecondUserId() {
        return secondUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_users_relation.second_user_id
     *
     * @param secondUserId the value for hai_users_relation.second_user_id
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    public void setSecondUserId(Long secondUserId) {
        this.secondUserId = secondUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_users_relation.third_user_id
     *
     * @return the value of hai_users_relation.third_user_id
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    public Long getThirdUserId() {
        return thirdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_users_relation.third_user_id
     *
     * @param thirdUserId the value for hai_users_relation.third_user_id
     *
     * @mbg.generated Wed Oct 25 08:54:16 CST 2017
     */
    public void setThirdUserId(Long thirdUserId) {
        this.thirdUserId = thirdUserId;
    }
}