package org.ehais.shop.model;

import java.io.Serializable;
import java.util.Date;

public class HaiWarehouse implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_warehouse.warehouse_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private Integer warehouseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_warehouse.warehouse_code
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private String warehouseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_warehouse.warehouse_name
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private String warehouseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_warehouse.store_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_warehouse.create_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_warehouse.update_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_warehouse.last_update_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_warehouse.create_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private Long createAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_warehouse.update_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private Long updateAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_warehouse.last_update_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private Long lastUpdateAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_warehouse.remark
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hai_warehouse
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_warehouse.warehouse_id
     *
     * @return the value of hai_warehouse.warehouse_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public Integer getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_warehouse.warehouse_id
     *
     * @param warehouseId the value for hai_warehouse.warehouse_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_warehouse.warehouse_code
     *
     * @return the value of hai_warehouse.warehouse_code
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public String getWarehouseCode() {
        return warehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_warehouse.warehouse_code
     *
     * @param warehouseCode the value for hai_warehouse.warehouse_code
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_warehouse.warehouse_name
     *
     * @return the value of hai_warehouse.warehouse_name
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public String getWarehouseName() {
        return warehouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_warehouse.warehouse_name
     *
     * @param warehouseName the value for hai_warehouse.warehouse_name
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_warehouse.store_id
     *
     * @return the value of hai_warehouse.store_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_warehouse.store_id
     *
     * @param storeId the value for hai_warehouse.store_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_warehouse.create_date
     *
     * @return the value of hai_warehouse.create_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_warehouse.create_date
     *
     * @param createDate the value for hai_warehouse.create_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_warehouse.update_date
     *
     * @return the value of hai_warehouse.update_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_warehouse.update_date
     *
     * @param updateDate the value for hai_warehouse.update_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_warehouse.last_update_date
     *
     * @return the value of hai_warehouse.last_update_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_warehouse.last_update_date
     *
     * @param lastUpdateDate the value for hai_warehouse.last_update_date
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_warehouse.create_admin_id
     *
     * @return the value of hai_warehouse.create_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public Long getCreateAdminId() {
        return createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_warehouse.create_admin_id
     *
     * @param createAdminId the value for hai_warehouse.create_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setCreateAdminId(Long createAdminId) {
        this.createAdminId = createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_warehouse.update_admin_id
     *
     * @return the value of hai_warehouse.update_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public Long getUpdateAdminId() {
        return updateAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_warehouse.update_admin_id
     *
     * @param updateAdminId the value for hai_warehouse.update_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setUpdateAdminId(Long updateAdminId) {
        this.updateAdminId = updateAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_warehouse.last_update_admin_id
     *
     * @return the value of hai_warehouse.last_update_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public Long getLastUpdateAdminId() {
        return lastUpdateAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_warehouse.last_update_admin_id
     *
     * @param lastUpdateAdminId the value for hai_warehouse.last_update_admin_id
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setLastUpdateAdminId(Long lastUpdateAdminId) {
        this.lastUpdateAdminId = lastUpdateAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_warehouse.remark
     *
     * @return the value of hai_warehouse.remark
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_warehouse.remark
     *
     * @param remark the value for hai_warehouse.remark
     *
     * @mbg.generated Tue Jun 12 17:22:45 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}