package org.ehais.epublic.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.ehais.epublic.model.HaiStoreStatistics;
import org.ehais.epublic.model.HaiStoreStatisticsExample;

public interface HaiStoreStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_store_statistics
     *
     * @mbg.generated Wed Sep 20 13:04:46 CST 2017
     */
    @Select("select count(*) from hai_store_statistics where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_store_statistics
     *
     * @mbg.generated Wed Sep 20 13:04:46 CST 2017
     */
    @Select("select count(*) from hai_store_statistics where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_store_statistics
     *
     * @mbg.generated Wed Sep 20 13:04:46 CST 2017
     */
    long countByExample(HaiStoreStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_store_statistics
     *
     * @mbg.generated Wed Sep 20 13:04:46 CST 2017
     */
    int deleteByExample(HaiStoreStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_store_statistics
     *
     * @mbg.generated Wed Sep 20 13:04:46 CST 2017
     */
    int deleteByPrimaryKey(Integer storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_store_statistics
     *
     * @mbg.generated Wed Sep 20 13:04:46 CST 2017
     */
    int insert(HaiStoreStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_store_statistics
     *
     * @mbg.generated Wed Sep 20 13:04:46 CST 2017
     */
    int insertSelective(HaiStoreStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_store_statistics
     *
     * @mbg.generated Wed Sep 20 13:04:46 CST 2017
     */
    List<HaiStoreStatistics> selectByExample(HaiStoreStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_store_statistics
     *
     * @mbg.generated Wed Sep 20 13:04:46 CST 2017
     */
    HaiStoreStatistics selectByPrimaryKey(Integer storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_store_statistics
     *
     * @mbg.generated Wed Sep 20 13:04:46 CST 2017
     */
    int updateByExampleSelective(@Param("record") HaiStoreStatistics record, @Param("example") HaiStoreStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_store_statistics
     *
     * @mbg.generated Wed Sep 20 13:04:46 CST 2017
     */
    int updateByExample(@Param("record") HaiStoreStatistics record, @Param("example") HaiStoreStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_store_statistics
     *
     * @mbg.generated Wed Sep 20 13:04:46 CST 2017
     */
    int updateByPrimaryKeySelective(HaiStoreStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_store_statistics
     *
     * @mbg.generated Wed Sep 20 13:04:46 CST 2017
     */
    int updateByPrimaryKey(HaiStoreStatistics record);
}