package org.ehais.epublic.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.ehais.epublic.model.ThinkRoleUserExample;
import org.ehais.epublic.model.ThinkRoleUserKey;

public interface ThinkRoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role_user
     *
     * @mbggenerated Mon Apr 11 23:09:51 CST 2016
     */
    @ResultMap(value = "BaseResultMap")
    List<ThinkRoleUserKey> think_role_user_list(@Param("store_id") Integer store_id, @Param("start") Integer start, @Param("len") Integer len);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role_user
     *
     * @mbggenerated Mon Apr 11 23:09:51 CST 2016
     */
    @ResultMap(value = "BaseResultMap")
    List<ThinkRoleUserKey> think_role_user_list_by_example(ThinkRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role_user
     *
     * @mbggenerated Mon Apr 11 23:09:51 CST 2016
     */
    int countByExample(ThinkRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role_user
     *
     * @mbggenerated Mon Apr 11 23:09:51 CST 2016
     */
    int deleteByExample(ThinkRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role_user
     *
     * @mbggenerated Mon Apr 11 23:09:51 CST 2016
     */
    int deleteByPrimaryKey(ThinkRoleUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role_user
     *
     * @mbggenerated Mon Apr 11 23:09:51 CST 2016
     */
    int insert(ThinkRoleUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role_user
     *
     * @mbggenerated Mon Apr 11 23:09:51 CST 2016
     */
    int insertSelective(ThinkRoleUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role_user
     *
     * @mbggenerated Mon Apr 11 23:09:51 CST 2016
     */
    List<ThinkRoleUserKey> selectByExample(ThinkRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role_user
     *
     * @mbggenerated Mon Apr 11 23:09:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") ThinkRoleUserKey record, @Param("example") ThinkRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role_user
     *
     * @mbggenerated Mon Apr 11 23:09:51 CST 2016
     */
    int updateByExample(@Param("record") ThinkRoleUserKey record, @Param("example") ThinkRoleUserExample example);
}