package org.ehais.epublic.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.ehais.epublic.model.ThinkRole;
import org.ehais.epublic.model.ThinkRoleExample;

public interface ThinkRoleMapper {
	
//	@Select("select t.* from think_role t left join think_role_admin u on t.id = u.role_id where u.admin_id = #{admin_id} limit 0,1")
//    @ResultMap(value = "BaseResultMap")
//    ThinkRole think_role_admin( @Param("admin_id") Integer admin_id);

	
//	@Select("select * from think_role_admin  where admin_id = #{admin_id} limit 0,1")
//    @ResultMap(value = "BaseRoleAdminMap")
//    List<ThinkRoleAdmin> think_role_admin( @Param("admin_id") Long admin_id);

    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbggenerated Mon Apr 11 23:09:51 CST 2016
     */
    @ResultMap(value = "BaseResultMap")
    List<ThinkRole> think_role_list(@Param("store_id") Integer store_id, @Param("start") Integer start, @Param("len") Integer len);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbggenerated Mon Apr 11 23:09:51 CST 2016
     */
    @ResultMap(value = "BaseResultMap")
    List<ThinkRole> think_role_list_by_example(ThinkRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbg.generated Sat Oct 28 22:42:58 CST 2017
     */
    @Select("select count(*) from think_role where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbg.generated Sat Oct 28 22:42:58 CST 2017
     */
    @Select("select count(*) from think_role where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbg.generated Sat Oct 28 22:42:58 CST 2017
     */
    long countByExample(ThinkRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbg.generated Sat Oct 28 22:42:58 CST 2017
     */
    int deleteByExample(ThinkRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbg.generated Sat Oct 28 22:42:58 CST 2017
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbg.generated Sat Oct 28 22:42:58 CST 2017
     */
    int insert(ThinkRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbg.generated Sat Oct 28 22:42:58 CST 2017
     */
    int insertSelective(ThinkRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbg.generated Sat Oct 28 22:42:58 CST 2017
     */
    List<ThinkRole> selectByExampleWithBLOBs(ThinkRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbg.generated Sat Oct 28 22:42:58 CST 2017
     */
    List<ThinkRole> selectByExample(ThinkRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbg.generated Sat Oct 28 22:42:58 CST 2017
     */
    ThinkRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbg.generated Sat Oct 28 22:42:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") ThinkRole record, @Param("example") ThinkRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbg.generated Sat Oct 28 22:42:58 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") ThinkRole record, @Param("example") ThinkRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbg.generated Sat Oct 28 22:42:58 CST 2017
     */
    int updateByExample(@Param("record") ThinkRole record, @Param("example") ThinkRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbg.generated Sat Oct 28 22:42:58 CST 2017
     */
    int updateByPrimaryKeySelective(ThinkRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbg.generated Sat Oct 28 22:42:58 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(ThinkRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table think_role
     *
     * @mbg.generated Sat Oct 28 22:42:58 CST 2017
     */
    int updateByPrimaryKey(ThinkRole record);
}