package org.ehais.weixin.model;

import java.io.Serializable;

public class WpSurveyCat implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_survey_cat.sur_cat_id
     *
     * @mbggenerated Wed Mar 09 23:01:10 CST 2016
     */
    private Integer surCatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_survey_cat.title
     *
     * @mbggenerated Wed Mar 09 23:01:10 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_survey_cat.wxid
     *
     * @mbggenerated Wed Mar 09 23:01:10 CST 2016
     */
    private Integer wxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_survey_cat.is_void
     *
     * @mbggenerated Wed Mar 09 23:01:10 CST 2016
     */
    private Short isVoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_survey_cat.order_sort
     *
     * @mbggenerated Wed Mar 09 23:01:10 CST 2016
     */
    private Integer orderSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wp_survey_cat
     *
     * @mbggenerated Wed Mar 09 23:01:10 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_survey_cat.sur_cat_id
     *
     * @return the value of wp_survey_cat.sur_cat_id
     *
     * @mbggenerated Wed Mar 09 23:01:10 CST 2016
     */
    public Integer getSurCatId() {
        return surCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_survey_cat.sur_cat_id
     *
     * @param surCatId the value for wp_survey_cat.sur_cat_id
     *
     * @mbggenerated Wed Mar 09 23:01:10 CST 2016
     */
    public void setSurCatId(Integer surCatId) {
        this.surCatId = surCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_survey_cat.title
     *
     * @return the value of wp_survey_cat.title
     *
     * @mbggenerated Wed Mar 09 23:01:10 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_survey_cat.title
     *
     * @param title the value for wp_survey_cat.title
     *
     * @mbggenerated Wed Mar 09 23:01:10 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_survey_cat.wxid
     *
     * @return the value of wp_survey_cat.wxid
     *
     * @mbggenerated Wed Mar 09 23:01:10 CST 2016
     */
    public Integer getWxid() {
        return wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_survey_cat.wxid
     *
     * @param wxid the value for wp_survey_cat.wxid
     *
     * @mbggenerated Wed Mar 09 23:01:10 CST 2016
     */
    public void setWxid(Integer wxid) {
        this.wxid = wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_survey_cat.is_void
     *
     * @return the value of wp_survey_cat.is_void
     *
     * @mbggenerated Wed Mar 09 23:01:10 CST 2016
     */
    public Short getIsVoid() {
        return isVoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_survey_cat.is_void
     *
     * @param isVoid the value for wp_survey_cat.is_void
     *
     * @mbggenerated Wed Mar 09 23:01:10 CST 2016
     */
    public void setIsVoid(Short isVoid) {
        this.isVoid = isVoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_survey_cat.order_sort
     *
     * @return the value of wp_survey_cat.order_sort
     *
     * @mbggenerated Wed Mar 09 23:01:10 CST 2016
     */
    public Integer getOrderSort() {
        return orderSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_survey_cat.order_sort
     *
     * @param orderSort the value for wp_survey_cat.order_sort
     *
     * @mbggenerated Wed Mar 09 23:01:10 CST 2016
     */
    public void setOrderSort(Integer orderSort) {
        this.orderSort = orderSort;
    }
}