package org.ehais.weixin.model;

import java.io.Serializable;

public class WpSurveyQuestionWithBLOBs extends WpSurveyQuestion implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_survey_question.intro
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_survey_question.extra
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    private String extra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wp_survey_question
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_survey_question.intro
     *
     * @return the value of wp_survey_question.intro
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_survey_question.intro
     *
     * @param intro the value for wp_survey_question.intro
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_survey_question.extra
     *
     * @return the value of wp_survey_question.extra
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_survey_question.extra
     *
     * @param extra the value for wp_survey_question.extra
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public void setExtra(String extra) {
        this.extra = extra;
    }
}