package org.ehais.weixin.model;

import java.io.Serializable;

public class WpSurveyQuestion implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_survey_question.id
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_survey_question.title
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_survey_question.cTime
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    private Integer ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_survey_question.token
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_survey_question.is_must
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    private Byte isMust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_survey_question.type
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_survey_question.survey_id
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    private Integer surveyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_survey_question.sort
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_survey_question.parent_id
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wp_survey_question.answer_code
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    private String answerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wp_survey_question
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_survey_question.id
     *
     * @return the value of wp_survey_question.id
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_survey_question.id
     *
     * @param id the value for wp_survey_question.id
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_survey_question.title
     *
     * @return the value of wp_survey_question.title
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_survey_question.title
     *
     * @param title the value for wp_survey_question.title
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_survey_question.cTime
     *
     * @return the value of wp_survey_question.cTime
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_survey_question.cTime
     *
     * @param ctime the value for wp_survey_question.cTime
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_survey_question.token
     *
     * @return the value of wp_survey_question.token
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_survey_question.token
     *
     * @param token the value for wp_survey_question.token
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_survey_question.is_must
     *
     * @return the value of wp_survey_question.is_must
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public Byte getIsMust() {
        return isMust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_survey_question.is_must
     *
     * @param isMust the value for wp_survey_question.is_must
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public void setIsMust(Byte isMust) {
        this.isMust = isMust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_survey_question.type
     *
     * @return the value of wp_survey_question.type
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_survey_question.type
     *
     * @param type the value for wp_survey_question.type
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_survey_question.survey_id
     *
     * @return the value of wp_survey_question.survey_id
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public Integer getSurveyId() {
        return surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_survey_question.survey_id
     *
     * @param surveyId the value for wp_survey_question.survey_id
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public void setSurveyId(Integer surveyId) {
        this.surveyId = surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_survey_question.sort
     *
     * @return the value of wp_survey_question.sort
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_survey_question.sort
     *
     * @param sort the value for wp_survey_question.sort
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_survey_question.parent_id
     *
     * @return the value of wp_survey_question.parent_id
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_survey_question.parent_id
     *
     * @param parentId the value for wp_survey_question.parent_id
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wp_survey_question.answer_code
     *
     * @return the value of wp_survey_question.answer_code
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public String getAnswerCode() {
        return answerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wp_survey_question.answer_code
     *
     * @param answerCode the value for wp_survey_question.answer_code
     *
     * @mbggenerated Wed Mar 09 13:52:26 CST 2016
     */
    public void setAnswerCode(String answerCode) {
        this.answerCode = answerCode;
    }
}