package org.ehais.shop.model.vtu;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.ehais.tools.CriteriaObject;

public class VtuShareExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    public VtuShareExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVtuShareIdIsNull() {
            addCriterion("vtu_share_id is null");
            return (Criteria) this;
        }

        public Criteria andVtuShareIdIsNotNull() {
            addCriterion("vtu_share_id is not null");
            return (Criteria) this;
        }

        public Criteria andVtuShareIdEqualTo(Long value) {
            addCriterion("vtu_share_id =", value, "vtuShareId");
            return (Criteria) this;
        }

        public Criteria andVtuShareIdNotEqualTo(Long value) {
            addCriterion("vtu_share_id <>", value, "vtuShareId");
            return (Criteria) this;
        }

        public Criteria andVtuShareIdGreaterThan(Long value) {
            addCriterion("vtu_share_id >", value, "vtuShareId");
            return (Criteria) this;
        }

        public Criteria andVtuShareIdGreaterThanOrEqualTo(Long value) {
            addCriterion("vtu_share_id >=", value, "vtuShareId");
            return (Criteria) this;
        }

        public Criteria andVtuShareIdLessThan(Long value) {
            addCriterion("vtu_share_id <", value, "vtuShareId");
            return (Criteria) this;
        }

        public Criteria andVtuShareIdLessThanOrEqualTo(Long value) {
            addCriterion("vtu_share_id <=", value, "vtuShareId");
            return (Criteria) this;
        }

        public Criteria andVtuShareIdIn(List<Long> values) {
            addCriterion("vtu_share_id in", values, "vtuShareId");
            return (Criteria) this;
        }

        public Criteria andVtuShareIdNotIn(List<Long> values) {
            addCriterion("vtu_share_id not in", values, "vtuShareId");
            return (Criteria) this;
        }

        public Criteria andVtuShareIdBetween(Long value1, Long value2) {
            addCriterion("vtu_share_id between", value1, value2, "vtuShareId");
            return (Criteria) this;
        }

        public Criteria andVtuShareIdNotBetween(Long value1, Long value2) {
            addCriterion("vtu_share_id not between", value1, value2, "vtuShareId");
            return (Criteria) this;
        }

        public Criteria andVtuIdIsNull() {
            addCriterion("vtu_id is null");
            return (Criteria) this;
        }

        public Criteria andVtuIdIsNotNull() {
            addCriterion("vtu_id is not null");
            return (Criteria) this;
        }

        public Criteria andVtuIdEqualTo(Long value) {
            addCriterion("vtu_id =", value, "vtuId");
            return (Criteria) this;
        }

        public Criteria andVtuIdNotEqualTo(Long value) {
            addCriterion("vtu_id <>", value, "vtuId");
            return (Criteria) this;
        }

        public Criteria andVtuIdGreaterThan(Long value) {
            addCriterion("vtu_id >", value, "vtuId");
            return (Criteria) this;
        }

        public Criteria andVtuIdGreaterThanOrEqualTo(Long value) {
            addCriterion("vtu_id >=", value, "vtuId");
            return (Criteria) this;
        }

        public Criteria andVtuIdLessThan(Long value) {
            addCriterion("vtu_id <", value, "vtuId");
            return (Criteria) this;
        }

        public Criteria andVtuIdLessThanOrEqualTo(Long value) {
            addCriterion("vtu_id <=", value, "vtuId");
            return (Criteria) this;
        }

        public Criteria andVtuIdIn(List<Long> values) {
            addCriterion("vtu_id in", values, "vtuId");
            return (Criteria) this;
        }

        public Criteria andVtuIdNotIn(List<Long> values) {
            addCriterion("vtu_id not in", values, "vtuId");
            return (Criteria) this;
        }

        public Criteria andVtuIdBetween(Long value1, Long value2) {
            addCriterion("vtu_id between", value1, value2, "vtuId");
            return (Criteria) this;
        }

        public Criteria andVtuIdNotBetween(Long value1, Long value2) {
            addCriterion("vtu_id not between", value1, value2, "vtuId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andVtuTimeIsNull() {
            addCriterion("vtu_time is null");
            return (Criteria) this;
        }

        public Criteria andVtuTimeIsNotNull() {
            addCriterion("vtu_time is not null");
            return (Criteria) this;
        }

        public Criteria andVtuTimeEqualTo(String value) {
            addCriterion("vtu_time =", value, "vtuTime");
            return (Criteria) this;
        }

        public Criteria andVtuTimeNotEqualTo(String value) {
            addCriterion("vtu_time <>", value, "vtuTime");
            return (Criteria) this;
        }

        public Criteria andVtuTimeGreaterThan(String value) {
            addCriterion("vtu_time >", value, "vtuTime");
            return (Criteria) this;
        }

        public Criteria andVtuTimeGreaterThanOrEqualTo(String value) {
            addCriterion("vtu_time >=", value, "vtuTime");
            return (Criteria) this;
        }

        public Criteria andVtuTimeLessThan(String value) {
            addCriterion("vtu_time <", value, "vtuTime");
            return (Criteria) this;
        }

        public Criteria andVtuTimeLessThanOrEqualTo(String value) {
            addCriterion("vtu_time <=", value, "vtuTime");
            return (Criteria) this;
        }

        public Criteria andVtuTimeLike(String value) {
            addCriterion("vtu_time like", value, "vtuTime");
            return (Criteria) this;
        }

        public Criteria andVtuTimeNotLike(String value) {
            addCriterion("vtu_time not like", value, "vtuTime");
            return (Criteria) this;
        }

        public Criteria andVtuTimeIn(List<String> values) {
            addCriterion("vtu_time in", values, "vtuTime");
            return (Criteria) this;
        }

        public Criteria andVtuTimeNotIn(List<String> values) {
            addCriterion("vtu_time not in", values, "vtuTime");
            return (Criteria) this;
        }

        public Criteria andVtuTimeBetween(String value1, String value2) {
            addCriterion("vtu_time between", value1, value2, "vtuTime");
            return (Criteria) this;
        }

        public Criteria andVtuTimeNotBetween(String value1, String value2) {
            addCriterion("vtu_time not between", value1, value2, "vtuTime");
            return (Criteria) this;
        }

        public Criteria andVtuPicIsNull() {
            addCriterion("vtu_pic is null");
            return (Criteria) this;
        }

        public Criteria andVtuPicIsNotNull() {
            addCriterion("vtu_pic is not null");
            return (Criteria) this;
        }

        public Criteria andVtuPicEqualTo(String value) {
            addCriterion("vtu_pic =", value, "vtuPic");
            return (Criteria) this;
        }

        public Criteria andVtuPicNotEqualTo(String value) {
            addCriterion("vtu_pic <>", value, "vtuPic");
            return (Criteria) this;
        }

        public Criteria andVtuPicGreaterThan(String value) {
            addCriterion("vtu_pic >", value, "vtuPic");
            return (Criteria) this;
        }

        public Criteria andVtuPicGreaterThanOrEqualTo(String value) {
            addCriterion("vtu_pic >=", value, "vtuPic");
            return (Criteria) this;
        }

        public Criteria andVtuPicLessThan(String value) {
            addCriterion("vtu_pic <", value, "vtuPic");
            return (Criteria) this;
        }

        public Criteria andVtuPicLessThanOrEqualTo(String value) {
            addCriterion("vtu_pic <=", value, "vtuPic");
            return (Criteria) this;
        }

        public Criteria andVtuPicLike(String value) {
            addCriterion("vtu_pic like", value, "vtuPic");
            return (Criteria) this;
        }

        public Criteria andVtuPicNotLike(String value) {
            addCriterion("vtu_pic not like", value, "vtuPic");
            return (Criteria) this;
        }

        public Criteria andVtuPicIn(List<String> values) {
            addCriterion("vtu_pic in", values, "vtuPic");
            return (Criteria) this;
        }

        public Criteria andVtuPicNotIn(List<String> values) {
            addCriterion("vtu_pic not in", values, "vtuPic");
            return (Criteria) this;
        }

        public Criteria andVtuPicBetween(String value1, String value2) {
            addCriterion("vtu_pic between", value1, value2, "vtuPic");
            return (Criteria) this;
        }

        public Criteria andVtuPicNotBetween(String value1, String value2) {
            addCriterion("vtu_pic not between", value1, value2, "vtuPic");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andIsShareIsNull() {
            addCriterion("is_share is null");
            return (Criteria) this;
        }

        public Criteria andIsShareIsNotNull() {
            addCriterion("is_share is not null");
            return (Criteria) this;
        }

        public Criteria andIsShareEqualTo(Boolean value) {
            addCriterion("is_share =", value, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareNotEqualTo(Boolean value) {
            addCriterion("is_share <>", value, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareGreaterThan(Boolean value) {
            addCriterion("is_share >", value, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_share >=", value, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareLessThan(Boolean value) {
            addCriterion("is_share <", value, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareLessThanOrEqualTo(Boolean value) {
            addCriterion("is_share <=", value, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareIn(List<Boolean> values) {
            addCriterion("is_share in", values, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareNotIn(List<Boolean> values) {
            addCriterion("is_share not in", values, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareBetween(Boolean value1, Boolean value2) {
            addCriterion("is_share between", value1, value2, "isShare");
            return (Criteria) this;
        }

        public Criteria andIsShareNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_share not between", value1, value2, "isShare");
            return (Criteria) this;
        }

        public Criteria andShareTimeIsNull() {
            addCriterion("share_time is null");
            return (Criteria) this;
        }

        public Criteria andShareTimeIsNotNull() {
            addCriterion("share_time is not null");
            return (Criteria) this;
        }

        public Criteria andShareTimeEqualTo(Date value) {
            addCriterion("share_time =", value, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeNotEqualTo(Date value) {
            addCriterion("share_time <>", value, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeGreaterThan(Date value) {
            addCriterion("share_time >", value, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("share_time >=", value, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeLessThan(Date value) {
            addCriterion("share_time <", value, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeLessThanOrEqualTo(Date value) {
            addCriterion("share_time <=", value, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeIn(List<Date> values) {
            addCriterion("share_time in", values, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeNotIn(List<Date> values) {
            addCriterion("share_time not in", values, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeBetween(Date value1, Date value2) {
            addCriterion("share_time between", value1, value2, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareTimeNotBetween(Date value1, Date value2) {
            addCriterion("share_time not between", value1, value2, "shareTime");
            return (Criteria) this;
        }

        public Criteria andShareCountIsNull() {
            addCriterion("share_count is null");
            return (Criteria) this;
        }

        public Criteria andShareCountIsNotNull() {
            addCriterion("share_count is not null");
            return (Criteria) this;
        }

        public Criteria andShareCountEqualTo(Integer value) {
            addCriterion("share_count =", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountNotEqualTo(Integer value) {
            addCriterion("share_count <>", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountGreaterThan(Integer value) {
            addCriterion("share_count >", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("share_count >=", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountLessThan(Integer value) {
            addCriterion("share_count <", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountLessThanOrEqualTo(Integer value) {
            addCriterion("share_count <=", value, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountIn(List<Integer> values) {
            addCriterion("share_count in", values, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountNotIn(List<Integer> values) {
            addCriterion("share_count not in", values, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountBetween(Integer value1, Integer value2) {
            addCriterion("share_count between", value1, value2, "shareCount");
            return (Criteria) this;
        }

        public Criteria andShareCountNotBetween(Integer value1, Integer value2) {
            addCriterion("share_count not between", value1, value2, "shareCount");
            return (Criteria) this;
        }

        public Criteria andVtuTimeLikeInsensitive(String value) {
            addCriterion("upper(vtu_time) like", value.toUpperCase(), "vtuTime");
            return (Criteria) this;
        }

        public Criteria andVtuPicLikeInsensitive(String value) {
            addCriterion("upper(vtu_pic) like", value.toUpperCase(), "vtuPic");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vtu_share
     *
     * @mbg.generated do_not_delete_during_merge Sat Sep 16 10:28:10 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vtu_share
     *
     * @mbg.generated Sat Sep 16 10:28:10 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}