package org.ehais.project.model;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class ProPlan implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_plan.plan_id
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    private Integer planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_plan.task_id
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_plan.plan_title
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    private String planTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_plan.pro_id
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    private Integer proId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_plan.plan_start_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    @DateTimeFormat( pattern = "yyyy-MM-dd" )
    private Date planStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_plan.plan_end_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    @DateTimeFormat( pattern = "yyyy-MM-dd" )
    private Date planEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_plan.truth_start_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    @DateTimeFormat( pattern = "yyyy-MM-dd" )
    private Date truthStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_plan.truth_end_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    @DateTimeFormat( pattern = "yyyy-MM-dd" )
    private Date truthEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_plan.user_id
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_plan.dispatch_user_id
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    private Integer dispatchUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_plan.progress
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    private Integer progress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_plan.create_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_plan.update_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pro_plan
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_plan.plan_id
     *
     * @return the value of pro_plan.plan_id
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_plan.plan_id
     *
     * @param planId the value for pro_plan.plan_id
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_plan.task_id
     *
     * @return the value of pro_plan.task_id
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_plan.task_id
     *
     * @param taskId the value for pro_plan.task_id
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_plan.plan_title
     *
     * @return the value of pro_plan.plan_title
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public String getPlanTitle() {
        return planTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_plan.plan_title
     *
     * @param planTitle the value for pro_plan.plan_title
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public void setPlanTitle(String planTitle) {
        this.planTitle = planTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_plan.pro_id
     *
     * @return the value of pro_plan.pro_id
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_plan.pro_id
     *
     * @param proId the value for pro_plan.pro_id
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_plan.plan_start_date
     *
     * @return the value of pro_plan.plan_start_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public Date getPlanStartDate() {
        return planStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_plan.plan_start_date
     *
     * @param planStartDate the value for pro_plan.plan_start_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public void setPlanStartDate(Date planStartDate) {
        this.planStartDate = planStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_plan.plan_end_date
     *
     * @return the value of pro_plan.plan_end_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public Date getPlanEndDate() {
        return planEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_plan.plan_end_date
     *
     * @param planEndDate the value for pro_plan.plan_end_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public void setPlanEndDate(Date planEndDate) {
        this.planEndDate = planEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_plan.truth_start_date
     *
     * @return the value of pro_plan.truth_start_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public Date getTruthStartDate() {
        return truthStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_plan.truth_start_date
     *
     * @param truthStartDate the value for pro_plan.truth_start_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public void setTruthStartDate(Date truthStartDate) {
        this.truthStartDate = truthStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_plan.truth_end_date
     *
     * @return the value of pro_plan.truth_end_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public Date getTruthEndDate() {
        return truthEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_plan.truth_end_date
     *
     * @param truthEndDate the value for pro_plan.truth_end_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public void setTruthEndDate(Date truthEndDate) {
        this.truthEndDate = truthEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_plan.user_id
     *
     * @return the value of pro_plan.user_id
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_plan.user_id
     *
     * @param userId the value for pro_plan.user_id
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_plan.dispatch_user_id
     *
     * @return the value of pro_plan.dispatch_user_id
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public Integer getDispatchUserId() {
        return dispatchUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_plan.dispatch_user_id
     *
     * @param dispatchUserId the value for pro_plan.dispatch_user_id
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public void setDispatchUserId(Integer dispatchUserId) {
        this.dispatchUserId = dispatchUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_plan.progress
     *
     * @return the value of pro_plan.progress
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public Integer getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_plan.progress
     *
     * @param progress the value for pro_plan.progress
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public void setProgress(Integer progress) {
        this.progress = progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_plan.create_date
     *
     * @return the value of pro_plan.create_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_plan.create_date
     *
     * @param createDate the value for pro_plan.create_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_plan.update_date
     *
     * @return the value of pro_plan.update_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_plan.update_date
     *
     * @param updateDate the value for pro_plan.update_date
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}