package org.ehais.shop.model.project;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.ehais.tools.CriteriaObject;

public class HaiBegOffExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    public HaiBegOffExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    public void CriteriaStoreId(Criteria c, CriteriaObject co) {
        if(co == null || co.getOperator() == null)return ;
        if(co.getOperator().equals("eq")){
            c.andStoreIdEqualTo(co.getStoreId());
        }else if(co.getOperator().equals("in")){
            c.andStoreIdIn(co.getStoreList());
        }else if(co.getOperator().equals("user_eq")){
            c.andUserIdEqualTo(co.getUserId());
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBegoffIdIsNull() {
            addCriterion("begoff_id is null");
            return (Criteria) this;
        }

        public Criteria andBegoffIdIsNotNull() {
            addCriterion("begoff_id is not null");
            return (Criteria) this;
        }

        public Criteria andBegoffIdEqualTo(Integer value) {
            addCriterion("begoff_id =", value, "begoffId");
            return (Criteria) this;
        }

        public Criteria andBegoffIdNotEqualTo(Integer value) {
            addCriterion("begoff_id <>", value, "begoffId");
            return (Criteria) this;
        }

        public Criteria andBegoffIdGreaterThan(Integer value) {
            addCriterion("begoff_id >", value, "begoffId");
            return (Criteria) this;
        }

        public Criteria andBegoffIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("begoff_id >=", value, "begoffId");
            return (Criteria) this;
        }

        public Criteria andBegoffIdLessThan(Integer value) {
            addCriterion("begoff_id <", value, "begoffId");
            return (Criteria) this;
        }

        public Criteria andBegoffIdLessThanOrEqualTo(Integer value) {
            addCriterion("begoff_id <=", value, "begoffId");
            return (Criteria) this;
        }

        public Criteria andBegoffIdIn(List<Integer> values) {
            addCriterion("begoff_id in", values, "begoffId");
            return (Criteria) this;
        }

        public Criteria andBegoffIdNotIn(List<Integer> values) {
            addCriterion("begoff_id not in", values, "begoffId");
            return (Criteria) this;
        }

        public Criteria andBegoffIdBetween(Integer value1, Integer value2) {
            addCriterion("begoff_id between", value1, value2, "begoffId");
            return (Criteria) this;
        }

        public Criteria andBegoffIdNotBetween(Integer value1, Integer value2) {
            addCriterion("begoff_id not between", value1, value2, "begoffId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andNumberIsNull() {
            addCriterion("number is null");
            return (Criteria) this;
        }

        public Criteria andNumberIsNotNull() {
            addCriterion("number is not null");
            return (Criteria) this;
        }

        public Criteria andNumberEqualTo(Integer value) {
            addCriterion("number =", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotEqualTo(Integer value) {
            addCriterion("number <>", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThan(Integer value) {
            addCriterion("number >", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("number >=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThan(Integer value) {
            addCriterion("number <", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThanOrEqualTo(Integer value) {
            addCriterion("number <=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberIn(List<Integer> values) {
            addCriterion("number in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotIn(List<Integer> values) {
            addCriterion("number not in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberBetween(Integer value1, Integer value2) {
            addCriterion("number between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("number not between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andTeacherUserIdIsNull() {
            addCriterion("teacher_user_id is null");
            return (Criteria) this;
        }

        public Criteria andTeacherUserIdIsNotNull() {
            addCriterion("teacher_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherUserIdEqualTo(Long value) {
            addCriterion("teacher_user_id =", value, "teacherUserId");
            return (Criteria) this;
        }

        public Criteria andTeacherUserIdNotEqualTo(Long value) {
            addCriterion("teacher_user_id <>", value, "teacherUserId");
            return (Criteria) this;
        }

        public Criteria andTeacherUserIdGreaterThan(Long value) {
            addCriterion("teacher_user_id >", value, "teacherUserId");
            return (Criteria) this;
        }

        public Criteria andTeacherUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("teacher_user_id >=", value, "teacherUserId");
            return (Criteria) this;
        }

        public Criteria andTeacherUserIdLessThan(Long value) {
            addCriterion("teacher_user_id <", value, "teacherUserId");
            return (Criteria) this;
        }

        public Criteria andTeacherUserIdLessThanOrEqualTo(Long value) {
            addCriterion("teacher_user_id <=", value, "teacherUserId");
            return (Criteria) this;
        }

        public Criteria andTeacherUserIdIn(List<Long> values) {
            addCriterion("teacher_user_id in", values, "teacherUserId");
            return (Criteria) this;
        }

        public Criteria andTeacherUserIdNotIn(List<Long> values) {
            addCriterion("teacher_user_id not in", values, "teacherUserId");
            return (Criteria) this;
        }

        public Criteria andTeacherUserIdBetween(Long value1, Long value2) {
            addCriterion("teacher_user_id between", value1, value2, "teacherUserId");
            return (Criteria) this;
        }

        public Criteria andTeacherUserIdNotBetween(Long value1, Long value2) {
            addCriterion("teacher_user_id not between", value1, value2, "teacherUserId");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveIsNull() {
            addCriterion("teacher_approve is null");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveIsNotNull() {
            addCriterion("teacher_approve is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveEqualTo(Integer value) {
            addCriterion("teacher_approve =", value, "teacherApprove");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveNotEqualTo(Integer value) {
            addCriterion("teacher_approve <>", value, "teacherApprove");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveGreaterThan(Integer value) {
            addCriterion("teacher_approve >", value, "teacherApprove");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveGreaterThanOrEqualTo(Integer value) {
            addCriterion("teacher_approve >=", value, "teacherApprove");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveLessThan(Integer value) {
            addCriterion("teacher_approve <", value, "teacherApprove");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveLessThanOrEqualTo(Integer value) {
            addCriterion("teacher_approve <=", value, "teacherApprove");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveIn(List<Integer> values) {
            addCriterion("teacher_approve in", values, "teacherApprove");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveNotIn(List<Integer> values) {
            addCriterion("teacher_approve not in", values, "teacherApprove");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveBetween(Integer value1, Integer value2) {
            addCriterion("teacher_approve between", value1, value2, "teacherApprove");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveNotBetween(Integer value1, Integer value2) {
            addCriterion("teacher_approve not between", value1, value2, "teacherApprove");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveTimeIsNull() {
            addCriterion("teacher_approve_time is null");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveTimeIsNotNull() {
            addCriterion("teacher_approve_time is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveTimeEqualTo(Date value) {
            addCriterion("teacher_approve_time =", value, "teacherApproveTime");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveTimeNotEqualTo(Date value) {
            addCriterion("teacher_approve_time <>", value, "teacherApproveTime");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveTimeGreaterThan(Date value) {
            addCriterion("teacher_approve_time >", value, "teacherApproveTime");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("teacher_approve_time >=", value, "teacherApproveTime");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveTimeLessThan(Date value) {
            addCriterion("teacher_approve_time <", value, "teacherApproveTime");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveTimeLessThanOrEqualTo(Date value) {
            addCriterion("teacher_approve_time <=", value, "teacherApproveTime");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveTimeIn(List<Date> values) {
            addCriterion("teacher_approve_time in", values, "teacherApproveTime");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveTimeNotIn(List<Date> values) {
            addCriterion("teacher_approve_time not in", values, "teacherApproveTime");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveTimeBetween(Date value1, Date value2) {
            addCriterion("teacher_approve_time between", value1, value2, "teacherApproveTime");
            return (Criteria) this;
        }

        public Criteria andTeacherApproveTimeNotBetween(Date value1, Date value2) {
            addCriterion("teacher_approve_time not between", value1, value2, "teacherApproveTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentUserIdIsNull() {
            addCriterion("department_user_id is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentUserIdIsNotNull() {
            addCriterion("department_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentUserIdEqualTo(Long value) {
            addCriterion("department_user_id =", value, "departmentUserId");
            return (Criteria) this;
        }

        public Criteria andDepartmentUserIdNotEqualTo(Long value) {
            addCriterion("department_user_id <>", value, "departmentUserId");
            return (Criteria) this;
        }

        public Criteria andDepartmentUserIdGreaterThan(Long value) {
            addCriterion("department_user_id >", value, "departmentUserId");
            return (Criteria) this;
        }

        public Criteria andDepartmentUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("department_user_id >=", value, "departmentUserId");
            return (Criteria) this;
        }

        public Criteria andDepartmentUserIdLessThan(Long value) {
            addCriterion("department_user_id <", value, "departmentUserId");
            return (Criteria) this;
        }

        public Criteria andDepartmentUserIdLessThanOrEqualTo(Long value) {
            addCriterion("department_user_id <=", value, "departmentUserId");
            return (Criteria) this;
        }

        public Criteria andDepartmentUserIdIn(List<Long> values) {
            addCriterion("department_user_id in", values, "departmentUserId");
            return (Criteria) this;
        }

        public Criteria andDepartmentUserIdNotIn(List<Long> values) {
            addCriterion("department_user_id not in", values, "departmentUserId");
            return (Criteria) this;
        }

        public Criteria andDepartmentUserIdBetween(Long value1, Long value2) {
            addCriterion("department_user_id between", value1, value2, "departmentUserId");
            return (Criteria) this;
        }

        public Criteria andDepartmentUserIdNotBetween(Long value1, Long value2) {
            addCriterion("department_user_id not between", value1, value2, "departmentUserId");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveIsNull() {
            addCriterion("department_approve is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveIsNotNull() {
            addCriterion("department_approve is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveEqualTo(Integer value) {
            addCriterion("department_approve =", value, "departmentApprove");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveNotEqualTo(Integer value) {
            addCriterion("department_approve <>", value, "departmentApprove");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveGreaterThan(Integer value) {
            addCriterion("department_approve >", value, "departmentApprove");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveGreaterThanOrEqualTo(Integer value) {
            addCriterion("department_approve >=", value, "departmentApprove");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveLessThan(Integer value) {
            addCriterion("department_approve <", value, "departmentApprove");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveLessThanOrEqualTo(Integer value) {
            addCriterion("department_approve <=", value, "departmentApprove");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveIn(List<Integer> values) {
            addCriterion("department_approve in", values, "departmentApprove");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveNotIn(List<Integer> values) {
            addCriterion("department_approve not in", values, "departmentApprove");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveBetween(Integer value1, Integer value2) {
            addCriterion("department_approve between", value1, value2, "departmentApprove");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveNotBetween(Integer value1, Integer value2) {
            addCriterion("department_approve not between", value1, value2, "departmentApprove");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveTimeIsNull() {
            addCriterion("department_approve_time is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveTimeIsNotNull() {
            addCriterion("department_approve_time is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveTimeEqualTo(Date value) {
            addCriterion("department_approve_time =", value, "departmentApproveTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveTimeNotEqualTo(Date value) {
            addCriterion("department_approve_time <>", value, "departmentApproveTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveTimeGreaterThan(Date value) {
            addCriterion("department_approve_time >", value, "departmentApproveTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("department_approve_time >=", value, "departmentApproveTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveTimeLessThan(Date value) {
            addCriterion("department_approve_time <", value, "departmentApproveTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveTimeLessThanOrEqualTo(Date value) {
            addCriterion("department_approve_time <=", value, "departmentApproveTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveTimeIn(List<Date> values) {
            addCriterion("department_approve_time in", values, "departmentApproveTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveTimeNotIn(List<Date> values) {
            addCriterion("department_approve_time not in", values, "departmentApproveTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveTimeBetween(Date value1, Date value2) {
            addCriterion("department_approve_time between", value1, value2, "departmentApproveTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentApproveTimeNotBetween(Date value1, Date value2) {
            addCriterion("department_approve_time not between", value1, value2, "departmentApproveTime");
            return (Criteria) this;
        }

        public Criteria andLeaderUserIdIsNull() {
            addCriterion("leader_user_id is null");
            return (Criteria) this;
        }

        public Criteria andLeaderUserIdIsNotNull() {
            addCriterion("leader_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andLeaderUserIdEqualTo(Long value) {
            addCriterion("leader_user_id =", value, "leaderUserId");
            return (Criteria) this;
        }

        public Criteria andLeaderUserIdNotEqualTo(Long value) {
            addCriterion("leader_user_id <>", value, "leaderUserId");
            return (Criteria) this;
        }

        public Criteria andLeaderUserIdGreaterThan(Long value) {
            addCriterion("leader_user_id >", value, "leaderUserId");
            return (Criteria) this;
        }

        public Criteria andLeaderUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("leader_user_id >=", value, "leaderUserId");
            return (Criteria) this;
        }

        public Criteria andLeaderUserIdLessThan(Long value) {
            addCriterion("leader_user_id <", value, "leaderUserId");
            return (Criteria) this;
        }

        public Criteria andLeaderUserIdLessThanOrEqualTo(Long value) {
            addCriterion("leader_user_id <=", value, "leaderUserId");
            return (Criteria) this;
        }

        public Criteria andLeaderUserIdIn(List<Long> values) {
            addCriterion("leader_user_id in", values, "leaderUserId");
            return (Criteria) this;
        }

        public Criteria andLeaderUserIdNotIn(List<Long> values) {
            addCriterion("leader_user_id not in", values, "leaderUserId");
            return (Criteria) this;
        }

        public Criteria andLeaderUserIdBetween(Long value1, Long value2) {
            addCriterion("leader_user_id between", value1, value2, "leaderUserId");
            return (Criteria) this;
        }

        public Criteria andLeaderUserIdNotBetween(Long value1, Long value2) {
            addCriterion("leader_user_id not between", value1, value2, "leaderUserId");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveIsNull() {
            addCriterion("leader_approve is null");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveIsNotNull() {
            addCriterion("leader_approve is not null");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveEqualTo(Integer value) {
            addCriterion("leader_approve =", value, "leaderApprove");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveNotEqualTo(Integer value) {
            addCriterion("leader_approve <>", value, "leaderApprove");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveGreaterThan(Integer value) {
            addCriterion("leader_approve >", value, "leaderApprove");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveGreaterThanOrEqualTo(Integer value) {
            addCriterion("leader_approve >=", value, "leaderApprove");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveLessThan(Integer value) {
            addCriterion("leader_approve <", value, "leaderApprove");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveLessThanOrEqualTo(Integer value) {
            addCriterion("leader_approve <=", value, "leaderApprove");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveIn(List<Integer> values) {
            addCriterion("leader_approve in", values, "leaderApprove");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveNotIn(List<Integer> values) {
            addCriterion("leader_approve not in", values, "leaderApprove");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveBetween(Integer value1, Integer value2) {
            addCriterion("leader_approve between", value1, value2, "leaderApprove");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveNotBetween(Integer value1, Integer value2) {
            addCriterion("leader_approve not between", value1, value2, "leaderApprove");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveTimeIsNull() {
            addCriterion("leader_approve_time is null");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveTimeIsNotNull() {
            addCriterion("leader_approve_time is not null");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveTimeEqualTo(Date value) {
            addCriterion("leader_approve_time =", value, "leaderApproveTime");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveTimeNotEqualTo(Date value) {
            addCriterion("leader_approve_time <>", value, "leaderApproveTime");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveTimeGreaterThan(Date value) {
            addCriterion("leader_approve_time >", value, "leaderApproveTime");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("leader_approve_time >=", value, "leaderApproveTime");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveTimeLessThan(Date value) {
            addCriterion("leader_approve_time <", value, "leaderApproveTime");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveTimeLessThanOrEqualTo(Date value) {
            addCriterion("leader_approve_time <=", value, "leaderApproveTime");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveTimeIn(List<Date> values) {
            addCriterion("leader_approve_time in", values, "leaderApproveTime");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveTimeNotIn(List<Date> values) {
            addCriterion("leader_approve_time not in", values, "leaderApproveTime");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveTimeBetween(Date value1, Date value2) {
            addCriterion("leader_approve_time between", value1, value2, "leaderApproveTime");
            return (Criteria) this;
        }

        public Criteria andLeaderApproveTimeNotBetween(Date value1, Date value2) {
            addCriterion("leader_approve_time not between", value1, value2, "leaderApproveTime");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNull() {
            addCriterion("store_id is null");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNotNull() {
            addCriterion("store_id is not null");
            return (Criteria) this;
        }

        public Criteria andStoreIdEqualTo(Integer value) {
            addCriterion("store_id =", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotEqualTo(Integer value) {
            addCriterion("store_id <>", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThan(Integer value) {
            addCriterion("store_id >", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("store_id >=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThan(Integer value) {
            addCriterion("store_id <", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThanOrEqualTo(Integer value) {
            addCriterion("store_id <=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdIn(List<Integer> values) {
            addCriterion("store_id in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotIn(List<Integer> values) {
            addCriterion("store_id not in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdBetween(Integer value1, Integer value2) {
            addCriterion("store_id between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotBetween(Integer value1, Integer value2) {
            addCriterion("store_id not between", value1, value2, "storeId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hai_beg_off
     *
     * @mbg.generated do_not_delete_during_merge Sat Nov 04 17:37:13 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hai_beg_off
     *
     * @mbg.generated Sat Nov 04 17:37:13 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}