package org.ehais.shop.model.iwshop;

import java.io.Serializable;

public class ProductsInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_id
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_code
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private String productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_name
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_subname
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private String productSubname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_size
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private String productSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_cat
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Integer productCat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_brand
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Integer productBrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_readi
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Integer productReadi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_serial
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Integer productSerial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_weight
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private String productWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_online
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Byte productOnline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_credit
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Integer productCredit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_prom
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Integer productProm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_prom_limit
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Integer productPromLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_prom_limitdate
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private String productPromLimitdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_prom_limitdays
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Integer productPromLimitdays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_prom_discount
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Integer productPromDiscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_expfee
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Float productExpfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_supplier
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Integer productSupplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_storage
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private String productStorage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_origin
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private String productOrigin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_unit
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private String productUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_instocks
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Integer productInstocks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_indexes
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private String productIndexes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.supply_price
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Float supplyPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.sell_price
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Float sellPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.market_price
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Float marketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.catimg
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private String catimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.sort
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.is_delete
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products_info.product_url
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private String productUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table products_info
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_id
     *
     * @return the value of products_info.product_id
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_id
     *
     * @param productId the value for products_info.product_id
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_code
     *
     * @return the value of products_info.product_code
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_code
     *
     * @param productCode the value for products_info.product_code
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_name
     *
     * @return the value of products_info.product_name
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_name
     *
     * @param productName the value for products_info.product_name
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_subname
     *
     * @return the value of products_info.product_subname
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public String getProductSubname() {
        return productSubname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_subname
     *
     * @param productSubname the value for products_info.product_subname
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductSubname(String productSubname) {
        this.productSubname = productSubname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_size
     *
     * @return the value of products_info.product_size
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public String getProductSize() {
        return productSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_size
     *
     * @param productSize the value for products_info.product_size
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductSize(String productSize) {
        this.productSize = productSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_cat
     *
     * @return the value of products_info.product_cat
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Integer getProductCat() {
        return productCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_cat
     *
     * @param productCat the value for products_info.product_cat
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductCat(Integer productCat) {
        this.productCat = productCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_brand
     *
     * @return the value of products_info.product_brand
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Integer getProductBrand() {
        return productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_brand
     *
     * @param productBrand the value for products_info.product_brand
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductBrand(Integer productBrand) {
        this.productBrand = productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_readi
     *
     * @return the value of products_info.product_readi
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Integer getProductReadi() {
        return productReadi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_readi
     *
     * @param productReadi the value for products_info.product_readi
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductReadi(Integer productReadi) {
        this.productReadi = productReadi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_serial
     *
     * @return the value of products_info.product_serial
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Integer getProductSerial() {
        return productSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_serial
     *
     * @param productSerial the value for products_info.product_serial
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductSerial(Integer productSerial) {
        this.productSerial = productSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_weight
     *
     * @return the value of products_info.product_weight
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public String getProductWeight() {
        return productWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_weight
     *
     * @param productWeight the value for products_info.product_weight
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductWeight(String productWeight) {
        this.productWeight = productWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_online
     *
     * @return the value of products_info.product_online
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Byte getProductOnline() {
        return productOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_online
     *
     * @param productOnline the value for products_info.product_online
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductOnline(Byte productOnline) {
        this.productOnline = productOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_credit
     *
     * @return the value of products_info.product_credit
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Integer getProductCredit() {
        return productCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_credit
     *
     * @param productCredit the value for products_info.product_credit
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductCredit(Integer productCredit) {
        this.productCredit = productCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_prom
     *
     * @return the value of products_info.product_prom
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Integer getProductProm() {
        return productProm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_prom
     *
     * @param productProm the value for products_info.product_prom
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductProm(Integer productProm) {
        this.productProm = productProm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_prom_limit
     *
     * @return the value of products_info.product_prom_limit
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Integer getProductPromLimit() {
        return productPromLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_prom_limit
     *
     * @param productPromLimit the value for products_info.product_prom_limit
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductPromLimit(Integer productPromLimit) {
        this.productPromLimit = productPromLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_prom_limitdate
     *
     * @return the value of products_info.product_prom_limitdate
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public String getProductPromLimitdate() {
        return productPromLimitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_prom_limitdate
     *
     * @param productPromLimitdate the value for products_info.product_prom_limitdate
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductPromLimitdate(String productPromLimitdate) {
        this.productPromLimitdate = productPromLimitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_prom_limitdays
     *
     * @return the value of products_info.product_prom_limitdays
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Integer getProductPromLimitdays() {
        return productPromLimitdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_prom_limitdays
     *
     * @param productPromLimitdays the value for products_info.product_prom_limitdays
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductPromLimitdays(Integer productPromLimitdays) {
        this.productPromLimitdays = productPromLimitdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_prom_discount
     *
     * @return the value of products_info.product_prom_discount
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Integer getProductPromDiscount() {
        return productPromDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_prom_discount
     *
     * @param productPromDiscount the value for products_info.product_prom_discount
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductPromDiscount(Integer productPromDiscount) {
        this.productPromDiscount = productPromDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_expfee
     *
     * @return the value of products_info.product_expfee
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Float getProductExpfee() {
        return productExpfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_expfee
     *
     * @param productExpfee the value for products_info.product_expfee
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductExpfee(Float productExpfee) {
        this.productExpfee = productExpfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_supplier
     *
     * @return the value of products_info.product_supplier
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Integer getProductSupplier() {
        return productSupplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_supplier
     *
     * @param productSupplier the value for products_info.product_supplier
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductSupplier(Integer productSupplier) {
        this.productSupplier = productSupplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_storage
     *
     * @return the value of products_info.product_storage
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public String getProductStorage() {
        return productStorage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_storage
     *
     * @param productStorage the value for products_info.product_storage
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductStorage(String productStorage) {
        this.productStorage = productStorage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_origin
     *
     * @return the value of products_info.product_origin
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public String getProductOrigin() {
        return productOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_origin
     *
     * @param productOrigin the value for products_info.product_origin
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductOrigin(String productOrigin) {
        this.productOrigin = productOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_unit
     *
     * @return the value of products_info.product_unit
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public String getProductUnit() {
        return productUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_unit
     *
     * @param productUnit the value for products_info.product_unit
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductUnit(String productUnit) {
        this.productUnit = productUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_instocks
     *
     * @return the value of products_info.product_instocks
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Integer getProductInstocks() {
        return productInstocks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_instocks
     *
     * @param productInstocks the value for products_info.product_instocks
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductInstocks(Integer productInstocks) {
        this.productInstocks = productInstocks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_indexes
     *
     * @return the value of products_info.product_indexes
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public String getProductIndexes() {
        return productIndexes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_indexes
     *
     * @param productIndexes the value for products_info.product_indexes
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductIndexes(String productIndexes) {
        this.productIndexes = productIndexes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.supply_price
     *
     * @return the value of products_info.supply_price
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Float getSupplyPrice() {
        return supplyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.supply_price
     *
     * @param supplyPrice the value for products_info.supply_price
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setSupplyPrice(Float supplyPrice) {
        this.supplyPrice = supplyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.sell_price
     *
     * @return the value of products_info.sell_price
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Float getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.sell_price
     *
     * @param sellPrice the value for products_info.sell_price
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setSellPrice(Float sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.market_price
     *
     * @return the value of products_info.market_price
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Float getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.market_price
     *
     * @param marketPrice the value for products_info.market_price
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setMarketPrice(Float marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.catimg
     *
     * @return the value of products_info.catimg
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public String getCatimg() {
        return catimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.catimg
     *
     * @param catimg the value for products_info.catimg
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setCatimg(String catimg) {
        this.catimg = catimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.sort
     *
     * @return the value of products_info.sort
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.sort
     *
     * @param sort the value for products_info.sort
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.is_delete
     *
     * @return the value of products_info.is_delete
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.is_delete
     *
     * @param isDelete the value for products_info.is_delete
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products_info.product_url
     *
     * @return the value of products_info.product_url
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public String getProductUrl() {
        return productUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products_info.product_url
     *
     * @param productUrl the value for products_info.product_url
     *
     * @mbg.generated Mon May 01 21:03:15 CST 2017
     */
    public void setProductUrl(String productUrl) {
        this.productUrl = productUrl;
    }
}