package org.ehais.shop.mapper.tp;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.ehais.shop.model.tp.TpDiningTable;
import org.ehais.shop.model.tp.TpDiningTableExample;

public interface TpDiningTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining_table
     *
     * @mbg.generated Fri Aug 18 14:09:36 CST 2017
     */
    @Select("select count(*) from tp_dining_table where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining_table
     *
     * @mbg.generated Fri Aug 18 14:09:36 CST 2017
     */
    @Select("select count(*) from tp_dining_table where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining_table
     *
     * @mbg.generated Fri Aug 18 14:09:36 CST 2017
     */
    long countByExample(TpDiningTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining_table
     *
     * @mbg.generated Fri Aug 18 14:09:36 CST 2017
     */
    int deleteByExample(TpDiningTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining_table
     *
     * @mbg.generated Fri Aug 18 14:09:36 CST 2017
     */
    int deleteByPrimaryKey(Long dtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining_table
     *
     * @mbg.generated Fri Aug 18 14:09:36 CST 2017
     */
    int insert(TpDiningTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining_table
     *
     * @mbg.generated Fri Aug 18 14:09:36 CST 2017
     */
    int insertSelective(TpDiningTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining_table
     *
     * @mbg.generated Fri Aug 18 14:09:36 CST 2017
     */
    List<TpDiningTable> selectByExample(TpDiningTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining_table
     *
     * @mbg.generated Fri Aug 18 14:09:36 CST 2017
     */
    TpDiningTable selectByPrimaryKey(Long dtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining_table
     *
     * @mbg.generated Fri Aug 18 14:09:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") TpDiningTable record, @Param("example") TpDiningTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining_table
     *
     * @mbg.generated Fri Aug 18 14:09:36 CST 2017
     */
    int updateByExample(@Param("record") TpDiningTable record, @Param("example") TpDiningTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining_table
     *
     * @mbg.generated Fri Aug 18 14:09:36 CST 2017
     */
    int updateByPrimaryKeySelective(TpDiningTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining_table
     *
     * @mbg.generated Fri Aug 18 14:09:36 CST 2017
     */
    int updateByPrimaryKey(TpDiningTable record);
}