package org.ehais.shop.mapper.tp;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.ehais.shop.model.tp.TpDining;
import org.ehais.shop.model.tp.TpDiningExample;
import org.ehais.shop.model.tp.TpDiningWithBLOBs;

public interface TpDiningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining
     *
     * @mbg.generated Sun Aug 06 21:16:43 CST 2017
     */
    @Select("select count(*) from tp_dining where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining
     *
     * @mbg.generated Sun Aug 06 21:16:43 CST 2017
     */
    @Select("select count(*) from tp_dining where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining
     *
     * @mbg.generated Sun Aug 06 21:16:43 CST 2017
     */
    long countByExample(TpDiningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining
     *
     * @mbg.generated Sun Aug 06 21:16:43 CST 2017
     */
    int deleteByExample(TpDiningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining
     *
     * @mbg.generated Sun Aug 06 21:16:43 CST 2017
     */
    int deleteByPrimaryKey(Long goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining
     *
     * @mbg.generated Sun Aug 06 21:16:43 CST 2017
     */
    int insert(TpDiningWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining
     *
     * @mbg.generated Sun Aug 06 21:16:43 CST 2017
     */
    int insertSelective(TpDiningWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining
     *
     * @mbg.generated Sun Aug 06 21:16:43 CST 2017
     */
    List<TpDiningWithBLOBs> selectByExampleWithBLOBs(TpDiningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining
     *
     * @mbg.generated Sun Aug 06 21:16:43 CST 2017
     */
    List<TpDining> selectByExample(TpDiningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining
     *
     * @mbg.generated Sun Aug 06 21:16:43 CST 2017
     */
    TpDiningWithBLOBs selectByPrimaryKey(Long goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining
     *
     * @mbg.generated Sun Aug 06 21:16:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") TpDiningWithBLOBs record, @Param("example") TpDiningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining
     *
     * @mbg.generated Sun Aug 06 21:16:43 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") TpDiningWithBLOBs record, @Param("example") TpDiningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining
     *
     * @mbg.generated Sun Aug 06 21:16:43 CST 2017
     */
    int updateByExample(@Param("record") TpDining record, @Param("example") TpDiningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining
     *
     * @mbg.generated Sun Aug 06 21:16:43 CST 2017
     */
    int updateByPrimaryKeySelective(TpDiningWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining
     *
     * @mbg.generated Sun Aug 06 21:16:43 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TpDiningWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_dining
     *
     * @mbg.generated Sun Aug 06 21:16:43 CST 2017
     */
    int updateByPrimaryKey(TpDining record);
}