package org.ehais.project.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.ehais.project.model.ProPlan;
import org.ehais.project.model.ProPlanExample;
import org.ehais.project.model.ProPlanWithBLOBs;

public interface ProPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_plan
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    @ResultMap(value = "BaseResultMap")
    List<ProPlan> pro_plan_list(@Param("store_id") Integer store_id, @Param("start") Integer start, @Param("len") Integer len);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_plan
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    @ResultMap(value = "BaseResultMap")
    List<ProPlan> pro_plan_list_by_example(ProPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_plan
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    int countByExample(ProPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_plan
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    int deleteByExample(ProPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_plan
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    int deleteByPrimaryKey(Integer planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_plan
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    int insert(ProPlanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_plan
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    int insertSelective(ProPlanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_plan
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    List<ProPlanWithBLOBs> selectByExampleWithBLOBs(ProPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_plan
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    List<ProPlan> selectByExample(ProPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_plan
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    ProPlanWithBLOBs selectByPrimaryKey(Integer planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_plan
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProPlanWithBLOBs record, @Param("example") ProPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_plan
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") ProPlanWithBLOBs record, @Param("example") ProPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_plan
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    int updateByExample(@Param("record") ProPlan record, @Param("example") ProPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_plan
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    int updateByPrimaryKeySelective(ProPlanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_plan
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(ProPlanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_plan
     *
     * @mbggenerated Thu Mar 17 10:18:56 CST 2016
     */
    int updateByPrimaryKey(ProPlan record);
}