package com.ehais.huangbao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import com.ehais.huangbao.model.HaiActivityType;
import com.ehais.huangbao.model.HaiActivityTypeExample;

public interface HaiActivityTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_activity_type
	 * @mbggenerated  Thu Mar 03 14:01:53 CST 2016
	 */
	int countByExample(HaiActivityTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_activity_type
	 * @mbggenerated  Thu Mar 03 14:01:53 CST 2016
	 */
	int deleteByExample(HaiActivityTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_activity_type
	 * @mbggenerated  Thu Mar 03 14:01:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer actTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_activity_type
	 * @mbggenerated  Thu Mar 03 14:01:53 CST 2016
	 */
	int insert(HaiActivityType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_activity_type
	 * @mbggenerated  Thu Mar 03 14:01:53 CST 2016
	 */
	int insertSelective(HaiActivityType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_activity_type
	 * @mbggenerated  Thu Mar 03 14:01:53 CST 2016
	 */
	List<HaiActivityType> selectByExampleWithBLOBs(
			HaiActivityTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_activity_type
	 * @mbggenerated  Thu Mar 03 14:01:53 CST 2016
	 */
	List<HaiActivityType> selectByExample(HaiActivityTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_activity_type
	 * @mbggenerated  Thu Mar 03 14:01:53 CST 2016
	 */
	HaiActivityType selectByPrimaryKey(Integer actTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_activity_type
	 * @mbggenerated  Thu Mar 03 14:01:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HaiActivityType record,
			@Param("example") HaiActivityTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_activity_type
	 * @mbggenerated  Thu Mar 03 14:01:53 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") HaiActivityType record,
			@Param("example") HaiActivityTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_activity_type
	 * @mbggenerated  Thu Mar 03 14:01:53 CST 2016
	 */
	int updateByExample(@Param("record") HaiActivityType record,
			@Param("example") HaiActivityTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_activity_type
	 * @mbggenerated  Thu Mar 03 14:01:53 CST 2016
	 */
	int updateByPrimaryKeySelective(HaiActivityType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_activity_type
	 * @mbggenerated  Thu Mar 03 14:01:53 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(HaiActivityType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_activity_type
	 * @mbggenerated  Thu Mar 03 14:01:53 CST 2016
	 */
	int updateByPrimaryKey(HaiActivityType record);
}