package com.ehais.huangbao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;

import com.ehais.huangbao.model.HaiContribution;
import com.ehais.huangbao.model.HaiContributionExample;

public interface HaiContributionMapper {
	
	@ResultMap(value = "myBaseResultMap")
	public List<HaiContribution> hai_contribution_cate_list(
			@Param("store_id") Integer store_id,
			@Param("cat_code") String cat_code, 
			@Param("start") Integer start, 
			@Param("len") Integer len);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_contribution
     *
     * @mbggenerated Mon Mar 28 16:04:51 CST 2016
     */
    @ResultMap(value = "BaseResultMap")
    List<HaiContribution> hai_contribution_list(@Param("store_id") Integer store_id, @Param("start") Integer start, @Param("len") Integer len);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_contribution
     *
     * @mbggenerated Mon Mar 28 16:04:51 CST 2016
     */
    @ResultMap(value = "BaseResultMap")
    List<HaiContribution> hai_contribution_list_by_example(HaiContributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_contribution
     *
     * @mbggenerated Mon Mar 28 16:04:51 CST 2016
     */
    int countByExample(HaiContributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_contribution
     *
     * @mbggenerated Mon Mar 28 16:04:51 CST 2016
     */
    int deleteByExample(HaiContributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_contribution
     *
     * @mbggenerated Mon Mar 28 16:04:51 CST 2016
     */
    int deleteByPrimaryKey(Integer conId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_contribution
     *
     * @mbggenerated Mon Mar 28 16:04:51 CST 2016
     */
    int insert(HaiContribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_contribution
     *
     * @mbggenerated Mon Mar 28 16:04:51 CST 2016
     */
    int insertSelective(HaiContribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_contribution
     *
     * @mbggenerated Mon Mar 28 16:04:51 CST 2016
     */
    List<HaiContribution> selectByExampleWithBLOBs(HaiContributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_contribution
     *
     * @mbggenerated Mon Mar 28 16:04:51 CST 2016
     */
    List<HaiContribution> selectByExample(HaiContributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_contribution
     *
     * @mbggenerated Mon Mar 28 16:04:51 CST 2016
     */
    HaiContribution selectByPrimaryKey(Integer conId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_contribution
     *
     * @mbggenerated Mon Mar 28 16:04:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") HaiContribution record, @Param("example") HaiContributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_contribution
     *
     * @mbggenerated Mon Mar 28 16:04:51 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") HaiContribution record, @Param("example") HaiContributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_contribution
     *
     * @mbggenerated Mon Mar 28 16:04:51 CST 2016
     */
    int updateByExample(@Param("record") HaiContribution record, @Param("example") HaiContributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_contribution
     *
     * @mbggenerated Mon Mar 28 16:04:51 CST 2016
     */
    int updateByPrimaryKeySelective(HaiContribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_contribution
     *
     * @mbggenerated Mon Mar 28 16:04:51 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(HaiContribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_contribution
     *
     * @mbggenerated Mon Mar 28 16:04:51 CST 2016
     */
    int updateByPrimaryKey(HaiContribution record);
}