package org.ehais.epublic.mapper.alipay;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.ehais.epublic.model.alipay.AlipayNotifyUrl;
import org.ehais.epublic.model.alipay.AlipayNotifyUrlExample;

public interface AlipayNotifyUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_notify_url
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    @Select("select count(*) from alipay_notify_url where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_notify_url
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    @Select("select count(*) from alipay_notify_url where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_notify_url
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    int countByExample(AlipayNotifyUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_notify_url
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    int deleteByExample(AlipayNotifyUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_notify_url
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_notify_url
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    int insert(AlipayNotifyUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_notify_url
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    int insertSelective(AlipayNotifyUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_notify_url
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    List<AlipayNotifyUrl> selectByExample(AlipayNotifyUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_notify_url
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    AlipayNotifyUrl selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_notify_url
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    int updateByExampleSelective(@Param("record") AlipayNotifyUrl record, @Param("example") AlipayNotifyUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_notify_url
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    int updateByExample(@Param("record") AlipayNotifyUrl record, @Param("example") AlipayNotifyUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_notify_url
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    int updateByPrimaryKeySelective(AlipayNotifyUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_notify_url
     *
     * @mbggenerated Tue Dec 27 10:20:44 CST 2016
     */
    int updateByPrimaryKey(AlipayNotifyUrl record);
}